### ISSUE TITLE
Cleanup action tries to remove files that are being used

### ISSUE THREAD

**Issue by franeko** [inlife/nexrender#103]
I am getting this error:
```
[1cUEbHiqTeUx1q3moMQIa] cleaning up...
updating job 1cUEbHiqTeUx1q3moMQIa
[1cUEbHiqTeUx1q3moMQIa] error occurred: Error: EBUSY: resource busy or locked, unlink '(...)\AppData\Local\Temp\nexrender\1cUEbHiqTeUx1q3moMQIa\photo1.jpg'
    at Object.unlinkSync (fs.js:952:3)
    at fs.readdirSync.map.entry ((...)\nexrender_test\node_modules\@nexrender\core\src\tasks\cleanup.js:14:18)
    at Array.map (<anonymous>)
    at rmdirRecursively ((...)\nexrender_test\node_modules\@nexrender\core\src\tasks\cleanup.js:10:28)
    at module.exports ((...)\nexrender_test\node_modules\@nexrender\core\src\tasks\cleanup.js:26:9)
    at module.exports ((...)\nexrender_test\node_modules\@nexrender\core\src\helpers\state.js:8:12)
    at Promise.resolve.then.then.then.then.then.then.then.job ((...)\nexrender_test\node_modules\@nexrender\core\src\index.js:89:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I couldn't reliably reproduce this error. From my initial investigation this error means that the files are in use by some other program - most likely still by aerender. The error appears more often when the load on my CPU and Disk is around 100% - although not every time.

**Comment by inlife** [comment]
have you checked your task manager?
seems to me there should've been the aerendercore.exe process still running
that would explain why files couldn't be deleted
however im not sure why wouldn't it die, if rendering has (un)successfully finished
could you also provide output logs from the parent folder for that project id ?

maybe we will be able to figure out the reason

**Comment by franeko** [comment]
Please find the log below. My guess is that with high load on CPU and Disk the aerender.exe process closes a little bit later than cleanup starts but it's impossible to notice when checking task manager. 
I don't understand your code 100% but is it possible that actions in `@nexrender/core/src/index.js`, listed in lines `83-89` run asynchronously? 

```
aerender version 16.0.1x48
Using DXGI: Device: "Intel(R) HD Graphics 620" has dedicated video RAM (MB): 128 and has shared video RAM (MB): 4037 (Total: 4165 MB)
Unable to read VR Path Registry from C:\Users\(...)\AppData\Local\openvr\openvrpaths.vrpath
Running Script: C:\Users\(...)\AppData\Local\Temp\nexrender\1cUEbHiqTeUx1q3moMQIa\nexrender-1cUEbHiqTeUx1q3moMQIa-script.jsx
PROGRESS: Adding specified comp to Render Queue
PROGRESS:  2/20/2019 11:01:10 AM: Starting composition Comp 1.


PROGRESS:  Render Settings: Best Settings
PROGRESS:  Quality: Best
PROGRESS:  Resolution: Full
PROGRESS:  Size: 1280 x 720
PROGRESS:  Proxy Use: Use No Proxies
PROGRESS:  Effects: Current Settings
PROGRESS:  Disk Cache: Read Only
PROGRESS:  Color Depth: Current Settings
PROGRESS:  Frame Blending: On for Checked Layers
PROGRESS:  Field Render: Off
PROGRESS:  Pulldown: Off
PROGRESS:  Motion Blur: On for Checked Layers
PROGRESS:  Solos: Current Settings
PROGRESS:  Time Span: Custom
PROGRESS:  Start: 0:00:00:01
PROGRESS:  End: 0:00:08:00
PROGRESS:  Duration: 0:00:08:00
PROGRESS:  Frame Rate: 25.00 (comp)
PROGRESS:  Guide Layers: All Off
PROGRESS:  Skip Existing Files: Off
PROGRESS:  
PROGRESS:  Output Module: Lossless
PROGRESS:  Output To: (...)\AppData\Local\Temp\nexrender\1cUEbHiqTeUx1q3moMQIa\result.avi
PROGRESS:  Format: AVI
PROGRESS:  Output Info: None
PROGRESS:  Include: Project Link
PROGRESS:  Output Audio: On (if comp has audio)
PROGRESS:  Channels: RGB
PROGRESS:  Depth: Millions of Colors
PROGRESS:  Color: Premultiplied
PROGRESS:  Resize: -
PROGRESS:  Crop: -
PROGRESS:  Final Size: 1280 x 720
PROGRESS:  Profile: -
PROGRESS:  Post-Render Action: None
PROGRESS:  
PROGRESS:  0:00:00:01 (1): 0 Seconds
PROGRESS:  0:00:00:02 (2): 0 Seconds
PROGRESS:  0:00:00:03 (3): 0 Seconds
PROGRESS:  0:00:00:04 (4): 0 Seconds
PROGRESS:  0:00:00:05 (5): 0 Seconds
PROGRESS:  0:00:00:06 (6): 0 Seconds
PROGRESS:  0:00:00:07 (7): 0 Seconds
PROGRESS:  0:00:00:08 (8): 0 Seconds
PROGRESS:  0:00:00:09 (9): 0 Seconds
PROGRESS:  0:00:00:10 (10): 0 Seconds
PROGRESS:  0:00:00:11 (11): 0 Seconds
PROGRESS:  0:00:00:12 (12): 0 Seconds
PROGRESS:  0:00:00:13 (13): 0 Seconds
PROGRESS:  0:00:00:14 (14): 0 Seconds
PROGRESS:  0:00:00:15 (15): 0 Seconds
PROGRESS:  0:00:00:16 (16): 0 Seconds
PROGRESS:  0:00:00:17 (17): 0 Seconds
PROGRESS:  0:00:00:18 (18): 0 Seconds
PROGRESS:  0:00:00:19 (19): 0 Seconds
PROGRESS:  0:00:00:20 (20): 0 Seconds
PROGRESS:  0:00:00:21 (21): 0 Seconds
PROGRESS:  0:00:00:22 (22): 0 Seconds
PROGRESS:  0:00:00:23 (23): 0 Seconds
PROGRESS:  0:00:00:24 (24): 0 Seconds
PROGRESS:  0:00:01:00 (25): 1 Seconds
PROGRESS:  0:00:01:01 (26): 0 Seconds
PROGRESS:  0:00:01:02 (27): 0 Seconds
PROGRESS:  0:00:01:03 (28): 0 Seconds
PROGRESS:  0:00:01:04 (29): 0 Seconds
PROGRESS:  0:00:01:05 (30): 0 Seconds
PROGRESS:  0:00:01:06 (31): 0 Seconds
PROGRESS:  0:00:01:07 (32): 0 Seconds
PROGRESS:  0:00:01:08 (33): 0 Seconds
PROGRESS:  0:00:01:09 (34): 0 Seconds
PROGRESS:  0:00:01:10 (35): 0 Seconds
PROGRESS:  0:00:01:11 (36): 0 Seconds
PROGRESS:  0:00:01:12 (37): 0 Seconds
PROGRESS:  0:00:01:13 (38): 0 Seconds
PROGRESS:  0:00:01:14 (39): 0 Seconds
PROGRESS:  0:00:01:15 (40): 0 Seconds
PROGRESS:  0:00:01:16 (41): 0 Seconds
PROGRESS:  0:00:01:17 (42): 0 Seconds
PROGRESS:  0:00:01:18 (43): 1 Seconds
PROGRESS:  0:00:01:19 (44): 0 Seconds
PROGRESS:  0:00:01:20 (45): 0 Seconds
PROGRESS:  0:00:01:21 (46): 0 Seconds
PROGRESS:  0:00:01:22 (47): 0 Seconds
PROGRESS:  0:00:01:23 (48): 0 Seconds
PROGRESS:  0:00:01:24 (49): 0 Seconds
PROGRESS:  0:00:02:00 (50): 0 Seconds
PROGRESS:  0:00:02:01 (51): 0 Seconds
PROGRESS:  0:00:02:02 (52): 0 Seconds
PROGRESS:  0:00:02:03 (53): 0 Seconds
PROGRESS:  0:00:02:04 (54): 0 Seconds
PROGRESS:  0:00:02:05 (55): 0 Seconds
PROGRESS:  0:00:02:06 (56): 1 Seconds
PROGRESS:  0:00:02:07 (57): 0 Seconds
PROGRESS:  0:00:02:08 (58): 0 Seconds
PROGRESS:  0:00:02:10 (60): 0 Seconds
PROGRESS:  0:00:02:11 (61): 0 Seconds
PROGRESS:  0:00:02:12 (62): 0 Seconds
PROGRESS:  0:00:02:13 (63): 0 Seconds
PROGRESS:  0:00:02:14 (64): 0 Seconds
PROGRESS:  0:00:02:15 (65): 1 Seconds
PROGRESS:  0:00:02:16 (66): 0 Seconds
PROGRESS:  0:00:02:17 (67): 0 Seconds
PROGRESS:  0:00:02:18 (68): 0 Seconds
PROGRESS:  0:00:02:19 (69): 1 Seconds
PROGRESS:  0:00:02:20 (70): 0 Seconds
PROGRESS:  0:00:02:21 (71): 0 Seconds
PROGRESS:  0:00:02:22 (72): 0 Seconds
PROGRESS:  0:00:02:23 (73): 0 Seconds
PROGRESS:  0:00:02:24 (74): 1 Seconds
PROGRESS:  0:00:03:00 (75): 0 Seconds
PROGRESS:  0:00:03:01 (76): 0 Seconds
PROGRESS:  0:00:03:02 (77): 0 Seconds
PROGRESS:  0:00:03:03 (78): 0 Seconds
PROGRESS:  0:00:03:04 (79): 1 Seconds
PROGRESS:  0:00:03:05 (80): 0 Seconds
PROGRESS:  0:00:03:06 (81): 0 Seconds
PROGRESS:  0:00:03:07 (82): 0 Seconds
PROGRESS:  0:00:03:08 (83): 0 Seconds
PROGRESS:  0:00:03:09 (84): 0 Seconds
PROGRESS:  0:00:03:10 (85): 1 Seconds
PROGRESS:  0:00:03:11 (86): 0 Seconds
PROGRESS:  0:00:03:12 (87): 0 Seconds
PROGRESS:  0:00:03:13 (88): 0 Seconds
PROGRESS:  0:00:03:14 (89): 0 Seconds
PROGRESS:  0:00:03:15 (90): 1 Seconds
PROGRESS:  0:00:03:16 (91): 0 Seconds
PROGRESS:  0:00:03:17 (92): 0 Seconds
PROGRESS:  0:00:03:18 (93): 0 Seconds
PROGRESS:  0:00:03:19 (94): 0 Seconds
PROGRESS:  0:00:03:20 (95): 0 Seconds
PROGRESS:  0:00:03:21 (96): 0 Seconds
PROGRESS:  0:00:03:22 (97): 0 Seconds
PROGRESS:  0:00:03:23 (98): 0 Seconds
PROGRESS:  0:00:03:24 (99): 1 Seconds
PROGRESS:  0:00:04:00 (100): 0 Seconds
PROGRESS:  0:00:04:01 (101): 0 Seconds
PROGRESS:  0:00:04:02 (102): 0 Seconds
PROGRESS:  0:00:04:03 (103): 0 Seconds
PROGRESS:  0:00:04:04 (104): 0 Seconds
PROGRESS:  0:00:04:05 (105): 0 Seconds
PROGRESS:  0:00:04:06 (106): 0 Seconds
PROGRESS:  0:00:04:07 (107): 0 Seconds
PROGRESS:  0:00:04:08 (108): 0 Seconds
PROGRESS:  0:00:04:09 (109): 0 Seconds
PROGRESS:  0:00:04:10 (110): 0 Seconds
PROGRESS:  0:00:04:11 (111): 0 Seconds
PROGRESS:  0:00:04:12 (112): 0 Seconds
PROGRESS:  0:00:04:13 (113): 0 Seconds
PROGRESS:  0:00:04:14 (114): 0 Seconds
PROGRESS:  0:00:04:15 (115): 0 Seconds
PROGRESS:  0:00:04:16 (116): 0 Seconds
PROGRESS:  0:00:04:17 (117): 0 Seconds
PROGRESS:  0:00:04:18 (118): 1 Seconds
PROGRESS:  0:00:04:19 (119): 0 Seconds
PROGRESS:  0:00:04:20 (120): 1 Seconds
PROGRESS:  0:00:04:21 (121): 1 Seconds
PROGRESS:  0:00:04:22 (122): 1 Seconds
PROGRESS:  0:00:04:23 (123): 1 Seconds
PROGRESS:  0:00:04:24 (124): 0 Seconds
PROGRESS:  0:00:05:00 (125): 1 Seconds
PROGRESS:  0:00:05:01 (126): 0 Seconds
PROGRESS:  0:00:05:02 (127): 0 Seconds
PROGRESS:  0:00:05:03 (128): 0 Seconds
PROGRESS:  0:00:05:04 (129): 0 Seconds
PROGRESS:  0:00:05:05 (130): 0 Seconds
PROGRESS:  0:00:05:06 (131): 0 Seconds
PROGRESS:  0:00:05:07 (132): 1 Seconds
PROGRESS:  0:00:05:08 (133): 0 Seconds
PROGRESS:  0:00:05:09 (134): 0 Seconds
PROGRESS:  0:00:05:10 (135): 0 Seconds
PROGRESS:  0:00:05:11 (136): 0 Seconds
PROGRESS:  0:00:05:12 (137): 0 Seconds
PROGRESS:  0:00:05:13 (138): 0 Seconds
PROGRESS:  0:00:05:14 (139): 0 Seconds
PROGRESS:  0:00:05:15 (140): 0 Seconds
PROGRESS:  0:00:05:16 (141): 0 Seconds
PROGRESS:  0:00:05:17 (142): 0 Seconds
PROGRESS:  0:00:05:18 (143): 0 Seconds
PROGRESS:  0:00:05:19 (144): 0 Seconds
PROGRESS:  0:00:05:20 (145): 1 Seconds
PROGRESS:  0:00:05:21 (146): 0 Seconds
PROGRESS:  0:00:05:22 (147): 0 Seconds
PROGRESS:  0:00:05:23 (148): 0 Seconds
PROGRESS:  0:00:05:24 (149): 0 Seconds
PROGRESS:  0:00:06:00 (150): 0 Seconds
PROGRESS:  0:00:06:01 (151): 0 Seconds
PROGRESS:  0:00:06:02 (152): 0 Seconds
PROGRESS:  0:00:06:03 (153): 0 Seconds
PROGRESS:  0:00:06:04 (154): 1 Seconds
PROGRESS:  0:00:06:05 (155): 0 Seconds
PROGRESS:  0:00:06:06 (156): 0 Seconds
PROGRESS:  0:00:06:07 (157): 0 Seconds
PROGRESS:  0:00:06:08 (158): 0 Seconds
PROGRESS:  0:00:06:09 (159): 0 Seconds
PROGRESS:  0:00:06:10 (160): 0 Seconds
PROGRESS:  0:00:06:11 (161): 0 Seconds
PROGRESS:  0:00:06:12 (162): 0 Seconds
PROGRESS:  0:00:06:13 (163): 1 Seconds
PROGRESS:  0:00:06:14 (164): 0 Seconds
PROGRESS:  0:00:06:15 (165): 0 Seconds
PROGRESS:  0:00:06:16 (166): 0 Seconds
PROGRESS:  0:00:06:17 (167): 0 Seconds
PROGRESS:  0:00:06:18 (168): 0 Seconds
PROGRESS:  0:00:06:19 (169): 0 Seconds
PROGRESS:  0:00:06:20 (170): 1 Seconds
PROGRESS:  0:00:06:21 (171): 0 Seconds
PROGRESS:  0:00:06:22 (172): 0 Seconds
PROGRESS:  0:00:06:23 (173): 0 Seconds
PROGRESS:  0:00:06:24 (174): 0 Seconds
PROGRESS:  0:00:07:00 (175): 0 Seconds
PROGRESS:  0:00:07:01 (176): 0 Seconds
PROGRESS:  0:00:07:02 (177): 0 Seconds
PROGRESS:  0:00:07:03 (178): 0 Seconds
PROGRESS:  0:00:07:04 (179): 0 Seconds
PROGRESS:  0:00:07:05 (180): 0 Seconds
PROGRESS:  0:00:07:06 (181): 0 Seconds
PROGRESS:  0:00:07:07 (182): 0 Seconds
PROGRESS:  0:00:07:08 (183): 1 Seconds
PROGRESS:  0:00:07:09 (184): 0 Seconds
PROGRESS:  0:00:07:10 (185): 0 Seconds
PROGRESS:  0:00:07:11 (186): 0 Seconds
PROGRESS:  0:00:07:12 (187): 0 Seconds
PROGRESS:  0:00:07:13 (188): 0 Seconds
PROGRESS:  0:00:07:14 (189): 0 Seconds
PROGRESS:  0:00:07:15 (190): 0 Seconds
PROGRESS:  0:00:07:16 (191): 0 Seconds
PROGRESS:  0:00:07:17 (192): 0 Seconds
PROGRESS:  0:00:07:18 (193): 0 Seconds
PROGRESS:  0:00:07:19 (194): 0 Seconds
PROGRESS:  0:00:07:20 (195): 0 Seconds
PROGRESS:  0:00:07:21 (196): 0 Seconds
PROGRESS:  0:00:07:22 (197): 0 Seconds
PROGRESS:  0:00:07:23 (198): 0 Seconds
PROGRESS:  0:00:07:24 (199): 1 Seconds
PROGRESS:  0:00:08:00 (200): 0 Seconds
PROGRESS:  2/20/2019 11:01:34 AM: Finished composition Comp 1.



PROGRESS:  Total Time Elapsed: 23 Seconds
LoadLibrary "n" failed!
LoadLibrary "n" failed!
```

**Comment by inlife** [comment]
it is unlikely
the next action is called only after the previous has finished
https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/tasks/render.js#L90-L104

those are the lines responsible for handling the exit of arender.exe, maybe something goes bad there, and aerender.exe exits earlier than aerendercore.exe (which is as far as i understand spawned by arender.exe internally)

two last lines look a bit suspicious, i have a feeling that they cause arender.exe to fail before aerendercore.exe has finished rendering
```
LoadLibrary "n" failed!
LoadLibrary "n" failed!
```

**Comment by inlife** [comment]
we actually had a similar problem before: https://github.com/inlife/nexrender/issues/60

**Comment by franeko** [comment]
```
LoadLibrary "n" failed!
LoadLibrary "n" failed!
```
According to Adobe those lines are caused by insufficient access to AE folders. Those appear in all of my log files so I didn't connect them with the issue.

I am using AE 2019 and `aerender.exe` spawns a process called `AfterFX.com` and there is no `aerendercore.exe` but I guess it's the same.

**Comment by franeko** [comment]
I just got similar error - again it seems that some tasks run asynchronously:
```
[QbzGpTnO2fw9Cpu0tBjiL] cleaning up...
updating job QbzGpTnO2fw9Cpu0tBjiL
[QbzGpTnO2fw9Cpu0tBjiL] error occurred: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\(...)\AppData\Local\Temp\nexrender\QbzGpTnO2fw9Cpu0tBjiL'
    at Object.rmdirSync (fs.js:680:3)
    at rmdirRecursively ((...)e\nexrender_test\node_modules\@nexrender\core\src\tasks\cleanup.js:17:8)
    at module.exports ((...)\nexrender_test\node_modules\@nexrender\core\src\tasks\cleanup.js:26:9)
    at module.exports ((...)\nexrender_test\node_modules\@nexrender\core\src\helpers\state.js:8:12)
    at Promise.resolve.then.then.then.then.then.then.then.job ((...)\nexrender_test\node_modules\@nexrender\core\src\index.js:89:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by franeko** [comment]
@inlife do you think it might be connected with #73?

**Comment by inlife** [comment]
quite possibly, however adding that fix also was bringing additional problems
![image](https://user-images.githubusercontent.com/2182108/53088671-19804c00-3513-11e9-9b90-39eae7a81da2.png)

**Comment by inlife** [comment]
just simply killign aerendercore.exe would be a terrible idea, since it can damage other running instances on the machine or corrupt the output file

trying to check access for file and waiting till access is received might be a possible option, however can result in deadlock, unless timeout is set and also sounds quite bug-prone option

i'm not sure if there is a good way to approach this
