### ISSUE TITLE
result.avi: No such file or directory

### ISSUE THREAD

**Issue by rmondesilva** [inlife/nexrender#148]
```
c:\Apache24\htdocs\myproject>nexrender-cli --file myjob.json --binary="C:/Program Files/Adobe/Adobe After Effects CC 2015/Support Files/aerender"
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects CC 2015\Support Files\aerender.exe
adding default render-only-node license for After Effects at:
 - C:\Users\Richmond\Documents\Adobe\ae_render_only_node.txt
checking After Effects command line renderer patch...
command line patch already is in place
[9Bp-bV9lDv2xKyZx0YZcW] setting up job...
[9Bp-bV9lDv2xKyZx0YZcW] working directory is: C:\Users\Richmond\AppData\Local\Temp\nexrender\9Bp-bV9lDv2xKyZx0YZcW
[9Bp-bV9lDv2xKyZx0YZcW] downloading assets...
[9Bp-bV9lDv2xKyZx0YZcW] applying prerender actions...
[9Bp-bV9lDv2xKyZx0YZcW] running script assemble...
[9Bp-bV9lDv2xKyZx0YZcW] rendering job...
[9Bp-bV9lDv2xKyZx0YZcW] rendering took ~4.246 sec.
[9Bp-bV9lDv2xKyZx0YZcW] writing aerender job log to: C:\Users\Richmond\AppData\Local\Temp\nexrender\aerender-9Bp-bV9lDv2xKyZx0YZcW.log
[9Bp-bV9lDv2xKyZx0YZcW] applying postrender actions...
[9Bp-bV9lDv2xKyZx0YZcW] starting action-encode action (ffmpeg)
[9Bp-bV9lDv2xKyZx0YZcW] action-encode: input file C:\Users\Richmond\AppData\Local\Temp\nexrender\9Bp-bV9lDv2xKyZx0YZcW\result.avi
[9Bp-bV9lDv2xKyZx0YZcW] action-encode: output file C:\Users\Richmond\AppData\Local\Temp\nexrender\9Bp-bV9lDv2xKyZx0YZcW\encoded.mp4
[9Bp-bV9lDv2xKyZx0YZcW] ffmpeg version N-92486-g8f875a90c4 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth

[9Bp-bV9lDv2xKyZx0YZcW]   libavutil      56. 23.101 / 56. 23.101
  libavcodec     58. 39.100 / 58. 39.100
  libavformat    58. 22.100 / 58. 22.100
  libavdevice    58.  6.100 / 58.  6.100
  libavfilter     7. 44.100 /  7. 44.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
C:\Users\Richmond\AppData\Local\Temp\nexrender\9Bp-bV9lDv2xKyZx0YZcW\result.avi: No such file or directory

> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg)
    at requireg.catch.err (C:\Users\Richmond\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\actions.js:25:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Any idea what is wrong here? **Why looking for result.avi? I don't set it anywhere, is it default?** 

Here is my first myjob.json with that error: 
```
{
    "template": {
        "src": "file:///apache24/htdocs/myproject/test.aep",
        "composition": "render"
    },
    "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "D:/myresult.mp4"
            }
        ]
    }
}
```

I changed it to: 
```
{
    "template": {
        "src": "file:///apache24/htdocs/myproject/test.aep",
        "composition": "render"
    },
    "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "avi",
                "output": "result.avi"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "result.avi",
                "output": "D:/result.avi"
            }
        ]
    }
}
```

On hoping that it could be the problem but ...

It results to: 
```
c:\Apache24\htdocs\myproject>nexrender-cli --file myjob.json --binary="C:/Program Files/Adobe/Adobe After Effects CC 2015/Support Files/aerender"
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects CC 2015\Support Files\aerender.exe
adding default render-only-node license for After Effects at:
 - C:\Users\Richmond\Documents\Adobe\ae_render_only_node.txt
checking After Effects command line renderer patch...
command line patch already is in place
[4luLMYwYHL4g1bMIV1ExK] setting up job...
[4luLMYwYHL4g1bMIV1ExK] working directory is: C:\Users\Richmond\AppData\Local\Temp\nexrender\4luLMYwYHL4g1bMIV1ExK
[4luLMYwYHL4g1bMIV1ExK] downloading assets...
[4luLMYwYHL4g1bMIV1ExK] applying prerender actions...
[4luLMYwYHL4g1bMIV1ExK] running script assemble...
[4luLMYwYHL4g1bMIV1ExK] rendering job...
[4luLMYwYHL4g1bMIV1ExK] rendering took ~4.215 sec.
[4luLMYwYHL4g1bMIV1ExK] writing aerender job log to: C:\Users\Richmond\AppData\Local\Temp\nexrender\aerender-4luLMYwYHL4g1bMIV1ExK.log
[4luLMYwYHL4g1bMIV1ExK] applying postrender actions...
[4luLMYwYHL4g1bMIV1ExK] starting action-encode action (ffmpeg)
[4luLMYwYHL4g1bMIV1ExK] action-encode: input file C:\Users\Richmond\AppData\Local\Temp\nexrender\4luLMYwYHL4g1bMIV1ExK\result.avi
[4luLMYwYHL4g1bMIV1ExK] action-encode: output file C:\Users\Richmond\AppData\Local\Temp\nexrender\4luLMYwYHL4g1bMIV1ExK\result.avi
> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: TypeError: Cannot convert undefined or null to object
    at requireg.catch.err (C:\Users\Richmond\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\actions.js:25:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I tried it on both Administrator mode and not.

**Comment by inlife** [comment]
rendering takes suspiciously short time, try checkout out the After Effects log located there, if im not mistaken: C:\Users\Richmond\AppData\Local\Temp\nexrender\4luLMYwYHL4g1bMIV1ExK.log

**Comment by rmondesilva** [comment]
Here is the content of that log:

```
aerender version 13.5x347
Using DXGI: Device: "NVIDIA GeForce GTX 1060 6GB" has dedicated video RAM (MB): 6052
2019-04-29 22:50:53 : INFO  Environment: Scale factor from PP is 1.000000
2019-04-29 22:50:53 : INFO  Environment: m_scaleFactor is 1.000000
WARNING:After Effects warning: Grouped_Message_{some layers have missing dependencies. Press Ctrl-C to copy this list.|||a layer has missing dependencies.###@0 dependencies are missing:}Text Layer: Font family: Bebas, Font style: Regular
WARNING:After Effects warning: Grouped_Message_{some layers have missing dependencies. Press Ctrl-C to copy this list.|||a layer has missing dependencies.###@0 dependencies are missing:}Text Layer: Font family: Roboto, Font style: Black
Running Script: C:\Users\Richmond\AppData\Local\Temp\nexrender\4luLMYwYHL4g1bMIV1ExK\nexrender-4luLMYwYHL4g1bMIV1ExK-script.jsx
aerender ERROR: No comp was found with the given name.
```

**Comment by rmondesilva** [comment]
Ok that log helps me. I found out that my composition name is not match on what I have on my aep file. But I corrected it and in the end, still same error.. but this time it shows some rendering happened:

CLI log: 
```
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects CC 2015\Support Files\aerender.exe
adding default render-only-node license for After Effects at:                                                            - C:\Users\Richmond\Documents\Adobe\ae_render_only_node.txt
checking After Effects command line renderer patch...
command line patch already is in place
[vSo37cYdM_qC0vfS7RC5j] setting up job...
[vSo37cYdM_qC0vfS7RC5j] working directory is: C:\Users\Richmond\AppData\Local\Temp\nexrender\vSo37cYdM_qC0vfS7RC5j
[vSo37cYdM_qC0vfS7RC5j] downloading assets...
[vSo37cYdM_qC0vfS7RC5j] applying prerender actions...
[vSo37cYdM_qC0vfS7RC5j] running script assemble...
[vSo37cYdM_qC0vfS7RC5j] rendering job...
[vSo37cYdM_qC0vfS7RC5j] rendering progress 0%...
[vSo37cYdM_qC0vfS7RC5j] rendering progress 1%...                                                                        [vSo37cYdM_qC0vfS7RC5j] rendering progress 21%...
[vSo37cYdM_qC0vfS7RC5j] rendering progress 40%...
[vSo37cYdM_qC0vfS7RC5j] rendering progress 41%...
[vSo37cYdM_qC0vfS7RC5j] rendering progress 61%...                                                                       [vSo37cYdM_qC0vfS7RC5j] rendering progress 80%...                                                                       [vSo37cYdM_qC0vfS7RC5j] rendering progress 81%...                                                                       [vSo37cYdM_qC0vfS7RC5j] rendering took ~11.995 sec.
[vSo37cYdM_qC0vfS7RC5j] writing aerender job log to: C:\Users\Richmond\AppData\Local\Temp\nexrender\aerender-vSo37cYdM_qC0vfS7RC5j.log                                                                                                          [vSo37cYdM_qC0vfS7RC5j] applying postrender actions...                                                                  [vSo37cYdM_qC0vfS7RC5j] starting action-encode action (ffmpeg)                                                          [vSo37cYdM_qC0vfS7RC5j] action-encode: input file C:\Users\Richmond\AppData\Local\Temp\nexrender\vSo37cYdM_qC0vfS7RC5j\result.avi                                                                                                               [vSo37cYdM_qC0vfS7RC5j] action-encode: output file C:\Users\Richmond\AppData\Local\Temp\nexrender\vSo37cYdM_qC0vfS7RC5j\result.avi                                                                                                              > job rendering failed                                                                                                  Error: Error loading postrender module @nexrender/action-encode: TypeError: Cannot convert undefined or null to object      at requireg.catch.err (C:\Users\Richmond\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\actions.js:25:35)                                                                                               at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Temp folder log: 
```
aerender version 13.5x347
Using DXGI: Device: "NVIDIA GeForce GTX 1060 6GB" has dedicated video RAM (MB): 6052
2019-04-30 01:59:12 : INFO  Environment: Scale factor from PP is 1.000000
2019-04-30 01:59:12 : INFO  Environment: m_scaleFactor is 1.000000
WARNING:After Effects warning: Grouped_Message_{some layers have missing dependencies. Press Ctrl-C to copy this list.|||a layer has missing dependencies.###@0 dependencies are missing:}Text Layer: Font family: Roboto, Font style: Black
Running Script: C:\Users\Richmond\AppData\Local\Temp\nexrender\vSo37cYdM_qC0vfS7RC5j\nexrender-vSo37cYdM_qC0vfS7RC5j-script.jsx
PROGRESS: Adding specified comp to Render Queue
PROGRESS:  4/30/2019 1:59:13 AM: Starting composition main.


PROGRESS:  Render Settings: Best Settings
PROGRESS:  Quality: Best
PROGRESS:  Resolution: Full
PROGRESS:  Size: 1920 x 1080
PROGRESS:  Proxy Use: Use No Proxies
PROGRESS:  Effects: Current Settings
PROGRESS:  Disk Cache: Read Only
PROGRESS:  Color Depth: Current Settings
PROGRESS:  Frame Blending: On for Checked Layers
PROGRESS:  Field Render: Off
PROGRESS:  Pulldown: Off
PROGRESS:  Motion Blur: On for Checked Layers
PROGRESS:  Solos: Current Settings
PROGRESS:  Time Span: Work Area
PROGRESS:  Start: 0:00:00:00
PROGRESS:  End: 0:00:04:24
PROGRESS:  Duration: 0:00:05:00
PROGRESS:  Frame Rate: 25.00 (comp)
PROGRESS:  Guide Layers: All Off
PROGRESS:  Skip Existing Files: Off
PROGRESS:  
PROGRESS:  Output Module: Lossless
PROGRESS:  Output To: C:\Users\Richmond\AppData\Local\Temp\nexrender\vSo37cYdM_qC0vfS7RC5j\result.avi
PROGRESS:  Format: AVI
PROGRESS:  Output Info: None
PROGRESS:  Include: Project Link
PROGRESS:  Output Audio: 48.000 kHz / 16 bit / Stereo (if comp has audio)
PROGRESS:  Channels: RGB
PROGRESS:  Depth: Millions of Colors
PROGRESS:  Color: Premultiplied
PROGRESS:  Resize: -
PROGRESS:  Crop: -
PROGRESS:  Final Size: 1920 x 1080
PROGRESS:  Profile:  -
PROGRESS:  Post-Render Action: None
PROGRESS:  
PROGRESS:  0:00:00:00 (1): 0 Seconds
PROGRESS:  0:00:00:01 (2): 0 Seconds
PROGRESS:  0:00:00:02 (3): 0 Seconds
PROGRESS:  0:00:00:03 (4): 0 Seconds
PROGRESS:  0:00:00:04 (5): 0 Seconds
PROGRESS:  0:00:00:05 (6): 0 Seconds
PROGRESS:  0:00:00:06 (7): 0 Seconds
PROGRESS:  0:00:00:07 (8): 0 Seconds
PROGRESS:  0:00:00:08 (9): 0 Seconds
PROGRESS:  0:00:00:09 (10): 0 Seconds
PROGRESS:  0:00:00:10 (11): 0 Seconds
PROGRESS:  0:00:00:11 (12): 0 Seconds
PROGRESS:  0:00:00:12 (13): 0 Seconds
PROGRESS:  0:00:00:13 (14): 0 Seconds
PROGRESS:  0:00:00:14 (15): 0 Seconds
PROGRESS:  0:00:00:15 (16): 0 Seconds
PROGRESS:  0:00:00:16 (17): 0 Seconds
PROGRESS:  0:00:00:17 (18): 0 Seconds
PROGRESS:  0:00:00:18 (19): 0 Seconds
PROGRESS:  0:00:00:19 (20): 0 Seconds
PROGRESS:  0:00:00:20 (21): 0 Seconds
PROGRESS:  0:00:00:21 (22): 1 Seconds
PROGRESS:  0:00:00:22 (23): 0 Seconds
PROGRESS:  0:00:00:23 (24): 0 Seconds
PROGRESS:  0:00:00:24 (25): 0 Seconds
PROGRESS:  0:00:01:00 (26): 0 Seconds
PROGRESS:  0:00:01:01 (27): 0 Seconds
PROGRESS:  0:00:01:02 (28): 0 Seconds
PROGRESS:  0:00:01:03 (29): 0 Seconds
PROGRESS:  0:00:01:04 (30): 0 Seconds
PROGRESS:  0:00:01:05 (31): 0 Seconds
PROGRESS:  0:00:01:06 (32): 0 Seconds
PROGRESS:  0:00:01:07 (33): 0 Seconds
PROGRESS:  0:00:01:08 (34): 0 Seconds
PROGRESS:  0:00:01:09 (35): 0 Seconds
PROGRESS:  0:00:01:10 (36): 0 Seconds
PROGRESS:  0:00:01:11 (37): 0 Seconds
PROGRESS:  0:00:01:12 (38): 0 Seconds
PROGRESS:  0:00:01:13 (39): 0 Seconds
PROGRESS:  0:00:01:14 (40): 0 Seconds
PROGRESS:  0:00:01:15 (41): 0 Seconds
PROGRESS:  0:00:01:16 (42): 1 Seconds
PROGRESS:  0:00:01:17 (43): 0 Seconds
PROGRESS:  0:00:01:18 (44): 0 Seconds
PROGRESS:  0:00:01:19 (45): 0 Seconds
PROGRESS:  0:00:01:20 (46): 0 Seconds
PROGRESS:  0:00:01:21 (47): 0 Seconds
PROGRESS:  0:00:01:22 (48): 0 Seconds
PROGRESS:  0:00:01:23 (49): 0 Seconds
PROGRESS:  0:00:01:24 (50): 0 Seconds
PROGRESS:  0:00:02:00 (51): 0 Seconds
PROGRESS:  0:00:02:01 (52): 0 Seconds
PROGRESS:  0:00:02:02 (53): 0 Seconds
PROGRESS:  0:00:02:03 (54): 0 Seconds
PROGRESS:  0:00:02:04 (55): 1 Seconds
PROGRESS:  0:00:02:05 (56): 0 Seconds
PROGRESS:  0:00:02:06 (57): 0 Seconds
PROGRESS:  0:00:02:07 (58): 0 Seconds
PROGRESS:  0:00:02:08 (59): 0 Seconds
PROGRESS:  0:00:02:09 (60): 0 Seconds
PROGRESS:  0:00:02:10 (61): 0 Seconds
PROGRESS:  0:00:02:11 (62): 0 Seconds
PROGRESS:  0:00:02:12 (63): 0 Seconds
PROGRESS:  0:00:02:13 (64): 0 Seconds
PROGRESS:  0:00:02:14 (65): 0 Seconds
PROGRESS:  0:00:02:15 (66): 0 Seconds
PROGRESS:  0:00:02:16 (67): 0 Seconds
PROGRESS:  0:00:02:17 (68): 0 Seconds
PROGRESS:  0:00:02:18 (69): 0 Seconds
PROGRESS:  0:00:02:19 (70): 0 Seconds
PROGRESS:  0:00:02:20 (71): 0 Seconds
PROGRESS:  0:00:02:21 (72): 1 Seconds
PROGRESS:  0:00:02:22 (73): 0 Seconds
PROGRESS:  0:00:02:23 (74): 0 Seconds
PROGRESS:  0:00:02:24 (75): 0 Seconds
PROGRESS:  0:00:03:00 (76): 0 Seconds
PROGRESS:  0:00:03:01 (77): 0 Seconds
PROGRESS:  0:00:03:02 (78): 0 Seconds
PROGRESS:  0:00:03:03 (79): 0 Seconds
PROGRESS:  0:00:03:04 (80): 0 Seconds
PROGRESS:  0:00:03:05 (81): 0 Seconds
PROGRESS:  0:00:03:06 (82): 0 Seconds
PROGRESS:  0:00:03:07 (83): 0 Seconds
PROGRESS:  0:00:03:08 (84): 0 Seconds
PROGRESS:  0:00:03:09 (85): 0 Seconds
PROGRESS:  0:00:03:10 (86): 0 Seconds
PROGRESS:  0:00:03:11 (87): 0 Seconds
PROGRESS:  0:00:03:12 (88): 0 Seconds
PROGRESS:  0:00:03:13 (89): 1 Seconds
PROGRESS:  0:00:03:14 (90): 0 Seconds
PROGRESS:  0:00:03:15 (91): 0 Seconds
PROGRESS:  0:00:03:16 (92): 0 Seconds
PROGRESS:  0:00:03:17 (93): 0 Seconds
PROGRESS:  0:00:03:18 (94): 0 Seconds
PROGRESS:  0:00:03:19 (95): 0 Seconds
PROGRESS:  0:00:03:20 (96): 0 Seconds
PROGRESS:  0:00:03:21 (97): 0 Seconds
PROGRESS:  0:00:03:22 (98): 0 Seconds
PROGRESS:  0:00:03:23 (99): 1 Seconds
PROGRESS:  0:00:03:24 (100): 0 Seconds
PROGRESS:  0:00:04:00 (101): 0 Seconds
PROGRESS:  0:00:04:01 (102): 0 Seconds
PROGRESS:  0:00:04:02 (103): 0 Seconds
PROGRESS:  0:00:04:03 (104): 0 Seconds
PROGRESS:  0:00:04:04 (105): 0 Seconds
PROGRESS:  0:00:04:05 (106): 0 Seconds
PROGRESS:  0:00:04:06 (107): 0 Seconds
PROGRESS:  0:00:04:07 (108): 0 Seconds
PROGRESS:  0:00:04:08 (109): 0 Seconds
PROGRESS:  0:00:04:09 (110): 0 Seconds
PROGRESS:  0:00:04:10 (111): 0 Seconds
PROGRESS:  0:00:04:11 (112): 0 Seconds
PROGRESS:  0:00:04:12 (113): 0 Seconds
PROGRESS:  0:00:04:13 (114): 0 Seconds
PROGRESS:  0:00:04:14 (115): 0 Seconds
PROGRESS:  0:00:04:15 (116): 1 Seconds
PROGRESS:  0:00:04:16 (117): 0 Seconds
PROGRESS:  0:00:04:17 (118): 0 Seconds
PROGRESS:  0:00:04:18 (119): 0 Seconds
PROGRESS:  0:00:04:19 (120): 0 Seconds
PROGRESS:  0:00:04:20 (121): 0 Seconds
PROGRESS:  0:00:04:21 (122): 0 Seconds
PROGRESS:  0:00:04:22 (123): 0 Seconds
PROGRESS:  0:00:04:23 (124): 0 Seconds
PROGRESS:  0:00:04:24 (125): 0 Seconds
PROGRESS:  4/30/2019 1:59:20 AM: Finished composition main.



PROGRESS:  Total Time Elapsed: 7 Seconds
```

**Comment by inlife** [comment]
i see that problem might be with the fact, that you are running action encode to and from the same file
```
[vSo37cYdM_qC0vfS7RC5j] action-encode: input file C:\Users\Richmond\AppData\Local\Temp\nexrender\vSo37cYdM_qC0vfS7RC5j\result.avi
[vSo37cYdM_qC0vfS7RC5j] action-encode: output file C:\Users\Richmond\AppData\Local\Temp\nexrender\vSo37cYdM_qC0vfS7RC5j\result.avi
```

and then you provide a different file for action-copy (encoded.mp4) which doesn't exist

**Comment by rmondesilva** [comment]
> i see that problem might be with the fact, that you are running action encode to and from the same file
> 
> ```
> [vSo37cYdM_qC0vfS7RC5j] action-encode: input file C:\Users\Richmond\AppData\Local\Temp\nexrender\vSo37cYdM_qC0vfS7RC5j\result.avi
> [vSo37cYdM_qC0vfS7RC5j] action-encode: output file C:\Users\Richmond\AppData\Local\Temp\nexrender\vSo37cYdM_qC0vfS7RC5j\result.avi
> ```
> 
> and then you provide a different file for action-copy (encoded.mp4) which doesn't exist

about encoded.mp4, No, I already changed myjob.json to this:

```
{
    "template": {
        "src": "file:///apache24/htdocs/codigoph/test.aep",
        "composition": "main"
    },
    "assets": [
        {
            "expression": "'CodigoPH'",
            "type": "data",
            "property": "Source Text",
            "layerName": "subscribe"
        }
    ],
    "actions": {
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "avi",
                "output": "result.avi"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "result.avi",
                "output": "D:/myresult.avi"
            }
        ]
    }
}
```
