### ISSUE TITLE
Missing module issue while running a job

### ISSUE THREAD

**Issue by CodeDem** [inlife/nexrender#212]
I'm trying to run a demo rendering via nexrender-cli but it throws following error

`Error: Couldn't find module @nexrender/provider-ile, Unknown protocol provided.`

**Comment by inlife** [comment]
Could you show your job json?

**Comment by CodeDem** [comment]
sure,
OS: macOS
installed nexrenderer via npm 

here it is
```
{
    "template": {
        "src": "ile:///Users/magicbox/Downloads/aeproject/projects/project.aep",
        "composition": "render"
    }
}
```


here is the complete error log

```
using automatically determined directory of After Effects installation:
 - /Applications/Adobe After Effects CC 2019/aerender
adding default render-only-node licenses for After Effects at:
 - /Users/magicbox/Documents/ae_render_only_node.txt
 - /Users/magicbox/Documents/Adobe/ae_render_only_node.txt
checking After Effects command line renderer patch...
command line patch already is in place
[DoEXSQXa3efshafFy91CL] setting up job...
[DoEXSQXa3efshafFy91CL] -- W A R N I N G: --

You haven't provided any post-render actions!
After render is finished all the files inside temporary folder (INCLUDING your target video) will be removed.

To prevent this from happening, please add an action to "job.actions.postrender".
For more info checkout: https://github.com/inlife/nexrender#Actions

P.S. to prevent nexrender from removing temp file data, you also can please provide an argument:
    --skip-cleanup (or skipCleanup: true if using programmatically)

[DoEXSQXa3efshafFy91CL] working directory is: /tmp/nexrender/DoEXSQXa3efshafFy91CL
[DoEXSQXa3efshafFy91CL] downloading assets...
> job rendering failed
Error: Couldn't find module @nexrender/provider-ile, Unknown protocol provided.
    at download (/snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/tasks/download.js:0:0)
    at module.exports (/snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/tasks/download.js:0:0)
    at module.exports (/snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/helpers/state.js:0:0)
    at Promise.resolve.then.then.job (/snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1315:13)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by CodeDem** [comment]
Ohh, I was so silly. I just checked my job.json file and I realized i misspelled file:// to ile://

**Comment by inlife** [comment]
oh, that happens :)
