### ISSUE TITLE
aerender ERROR -1701: AEGetParamPt failed at line 780

### ISSUE THREAD

**Issue by vc60er** [inlife/nexrender#223]
```shell
➜  Downloads sudo ./nexrender-cli-macos --file myjob.json --binary='/Applications/Adobe After Effects CC 2019/aerender'
> starting nexrender-cli
adding default render-only-node licenses for After Effects at:
 - /Users/chengning/Documents/ae_render_only_node.txt
 - /Users/chengning/Documents/Adobe/ae_render_only_node.txt
checking After Effects command line renderer patch...
command line patch already is in place
[qkDdCc1IQXpe7t71WH1OT] setting up job...
[qkDdCc1IQXpe7t71WH1OT] working directory is: /tmp/nexrender/qkDdCc1IQXpe7t71WH1OT
[qkDdCc1IQXpe7t71WH1OT] downloading assets...
[qkDdCc1IQXpe7t71WH1OT] applying prerender actions...
[qkDdCc1IQXpe7t71WH1OT] running script assemble...
[qkDdCc1IQXpe7t71WH1OT] rendering job...
[qkDdCc1IQXpe7t71WH1OT] rendering took ~64.474 sec.
[qkDdCc1IQXpe7t71WH1OT] writing aerender job log to: /tmp/nexrender/aerender-qkDdCc1IQXpe7t71WH1OT.log
[qkDdCc1IQXpe7t71WH1OT] applying postrender actions...
[qkDdCc1IQXpe7t71WH1OT] starting action-encode action (ffmpeg)
[qkDdCc1IQXpe7t71WH1OT] action-encode: input file /tmp/nexrender/qkDdCc1IQXpe7t71WH1OT/result.mov
[qkDdCc1IQXpe7t71WH1OT] action-encode: output file /tmp/nexrender/qkDdCc1IQXpe7t71WH1OT/encoded.mp4
[qkDdCc1IQXpe7t71WH1OT] ffmpeg version 4.1.3-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.3)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100

[qkDdCc1IQXpe7t71WH1OT] /tmp/nexrender/qkDdCc1IQXpe7t71WH1OT/result.mov: No such file or directory

> job rendering failed
Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg)
    at module.exports.PromiseSerial.map.requireg.catch.err (/snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/tasks/actions.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
➜  Downloads


➜  Downloads cat /tmp/nexrender/aerender-qkDdCc1IQXpe7t71WH1OT.log
aerender version 16.1.1x4
PROGRESS: Launching After Effects...
aerender ERROR -1701: AEGetParamPt failed at line 780

```

```json
{
    "template": {
        "src": "file:////Users/chengning/Downloads/老电影样式/Memories Slideshow/Memories Slideshow（已转换）.aep",
        "composition": "main"
    },
    "assets": [
        {
            "src": "file:////Users/Downloads/cn/cn.jpg",
            "type": "image",
            "layerName": "media_01"
        }
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4"
            },
            {
                "module": "@nexrender/action-copy",
                "input": "encoded.mp4",
                "output": "/Users/Downloads/myresult.mp4"
            }
        ]
    }
}
```

```shell
System version: macOS 10.14.6 (18G87)
```

**Comment by inlife** [comment]
Please check the contents of the temp folder, to see if any output is actually saved there

**Comment by inlife** [comment]
Looking at the error message seems like your after-effects fails to do the actual rendering.
I've found this thread, with a similar issue: https://forums.adobe.com/thread/2597380

**Comment by vc60er** [comment]
thansk you
