### ISSUE TITLE
Not running 

### ISSUE THREAD

**Issue by SamuelStag** [inlife/nexrender#303]
Hi, this project seems like a lifesaver and was really excited when i saw it. but then i've not been able to get it working, i tried running it on node but then i get the error; "Error: you should provide a proper path to After Effects' "aerender" binary", i tried manually directing it to the binary file then i got ; "errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: ...node_modules\\@nexrender\\core\\src\\Scripts\\Startup\\commandLineRenderer.jsx". can you help me with this?

**Comment by inlife** [comment]
Hello @SamuelStag 

Could you provide your nexrender version, your system name and version, as well as detailed log of the output and commands that you called.

**Comment by SamuelStag** [comment]
Hi, tha

> Hello @SamuelStag
> 
> Could you provide your nexrender version, your system name and version, as well as detailed log of the output and commands that you called.

Hi, thanks ... i'm using nexrender nexrender-patch-v1.0.0, 
i'm using an ZInox, and also the command i'm calling is 

        const result = await render(jobs, {
                workpath: 'C:/Users/zinox/Desktop/ay/react/aerender/src/component/workstation',
                binary: 'C:/Users/zinox/Desktop/ay/react/aerender/backend/node_modules/@nexrender/core/src/tasks',
                skipCleanup: true,
                addLicense: false,
                debug: true,
            })  
then i get the  error 

Error: ENOENT: no such file or directory, open 'C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\@nexrender\core\src\Scripts\Startup\commandLineRenderer.jsx'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:353:35)
    at module.exports (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\@nexrender\core\src\helpers\patch.js:20:21)
    at init (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\@nexrender\core\src\index.js:82:5)
    at render (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\@nexrender\core\src\index.js:90:20)
    at main (C:\Users\zinox\Desktop\ay\react\aerender\backend\server.js:22:34)
    at C:\Users\zinox\Desktop\ay\react\aerender\backend\server.js:31:9
    at Layer.handle [as handle_request] (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\express\lib\router\route.js:112:3) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\zinox\\Desktop\\ay\\react\\aerender\\backend\\node_modules\\@nexrender\\core\\src\\Scripts\\Startup\\commandLineRenderer.jsx'
}

**Comment by SamuelStag** [comment]
also if i simply do this command 
const result = await render(jobs)  
i get this 
Error: you should provide a proper path to After Effects' "aerender" binary
    at init (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\@nexrender\core\src\index.js:44:15)
    at render (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\@nexrender\core\src\index.js:90:20)
    at main (C:\Users\zinox\Desktop\ay\react\aerender\backend\server.js:22:34)
    at C:\Users\zinox\Desktop\ay\react\aerender\backend\server.js:25:9
    at Layer.handle [as handle_request] (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\zinox\Desktop\ay\react\aerender\backend\node_modules\express\lib\router\index.js:335:12)

**Comment by inlife** [comment]
> nexrender-patch-v1.0.0

I don't know about version like this, where did you get it?

Regarding the binary, the typical paths start like this: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/helpers/autofind.js#L17-L38
However, when you provide them manually, they should always have `aerender.exe` at the end.

> I'm using an ZInox

Unfortunately, I don't think I know what that is.

Also please, consider watching a video example made by one of our community members: https://www.youtube.com/watch?v=E64dXZ_AReQ

**Comment by SamuelStag** [comment]
> > nexrender-patch-v1.0.0
> 
> I don't know about version like this, where did you get it?
> 
> Regarding the binary, the typical paths start like this: https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/helpers/autofind.js#L17-L38
> However, when you provide them manually, they should always have `aerender.exe` at the end.
> Simply put: Make sure there is `aerender.exe` in the target folder, and provide an absolute path to it.
> 
> > I'm using an ZInox
> 
> Unfortunately, I don't think I know what that is.
> 
> Also please, consider watching a video example made by one of our community members: https://www.youtube.com/watch?v=E64dXZ_AReQ

i have watched it and still can't figure it out, and i can't even find a aerender.exe on my computer, i tried it on another system accer aspire 4830T yet it's still same thing ... and i downloaded the nexrender via npm

**Comment by inlife** [comment]
You can't run nexrender if you don't have `aerender.exe` on your computer. You **need** to have After Effects installed.
