### ISSUE TITLE
TypeError: `.matchAll` does not allow non-global regexes

### ISSUE THREAD

**Issue by FinnFrotscher** [inlife/nexrender#320]
**Describe the bug**
I had a series of bugs this morning, starting with a patch request.
Afterwards there where mutliple other kinds of issues. I have posted them in order of appearence.
I have updated all npm dependencies to the latest version and reintalled node modules.

All of these represent a seperate Run:

```
checking After Effects command line renderer patch...
backing up original command line script to:
 - /Applications/Adobe After Effects 2020/Backup.Scripts/Startup/commandLineRenderer.jsx
patching the command line script


              -- E R R O R --

you need to run application with admin priviledges once
to install Adobe After Effects commandLineRenderer.jsx patch

you might need to try to run nexrender with "sudo" only ONE TIME to install the patch


[nodemon] app crashed - waiting for file changes before starting...
```

```
aerender version 17.0.3x58
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

    at ChildProcess.<anonymous> (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/render.js:118:31)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

```
[ecx3wILp1ieObj0ApTnjR] rendering job...
error Error: Running Script: /Users/finnfrotscher/code/cofenster/api.renderer/tmp/ecx3wILp1ieObj0ApTnjR/nexrender-ecx3wILp1ieObj0ApTnjR-script.jsx
PROGRESS: Adding specified comp to Render Queue
aerender Error: After Effects error: Error in output for render queue item 1, output module 1. Can not create a file in directory /Users/finnfrotscher/code/cofenster/api.renderer/tmp/ecx3wILp1ieObj0ApTnjR. Try checking write permissions.
aerender version 17.0.3x58
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

    at ChildProcess.<anonymous> (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/render.js:118:31)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at Pipe.<anonymous> (net.js:664:12)
```
# this is the current issue
```
[OQ6sZPfaeiHnS95V3CRqv] setting up job...
[OQ6sZPfaeiHnS95V3CRqv] working directory is: /Users/finnfrotscher/code/cofenster/api.renderer/tmp/OQ6sZPfaeiHnS95V3CRqv
[OQ6sZPfaeiHnS95V3CRqv] downloading assets...
[OQ6sZPfaeiHnS95V3CRqv] applying prerender actions...
[OQ6sZPfaeiHnS95V3CRqv] running script assemble...
error TypeError: `.matchAll` does not allow non-global regexes
    at String.matchAll (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/core-js/modules/es.string.match-all.js:96:41)
    at EnhancedScript.findMissingMatchesInJSX (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:311:45)
    at EnhancedScript.build (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:448:14)
    at wrapEnhancedScript (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:462:27)
    at /Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:484:27
    at Array.map (<anonymous>)
    at module.exports (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:471:16)
    at module.exports (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/helpers/state.js:8:12)
    at /Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/index.js:97:22
    at runMicrotasks (<anonymous>)
```

**Information about environment**
```
   "@nexrender/action-copy": "^1.8.16",
    "@nexrender/action-encode": "^1.8.16",
    "@nexrender/core": "^1.12.0",
    "@nexrender/provider-s3": "^1.8.16",
```

**Comment by FinnFrotscher** [comment]
This is the entire output, with babel logging set to true:
```
[nodemon] starting `babel-node src/index.js`



loaded babel



@babel/preset-env: `DEBUG` option

Using targets:
{
  "node": "12.14.1"
}

Using modules transform: auto

Using plugins:
  proposal-nullish-coalescing-operator { "node":"12.14.1" }
  proposal-optional-chaining { "node":"12.14.1" }
  syntax-json-strings { "node":"12.14.1" }
  syntax-optional-catch-binding { "node":"12.14.1" }
  syntax-async-generators { "node":"12.14.1" }
  syntax-object-rest-spread { "node":"12.14.1" }
  transform-modules-commonjs { "node":"12.14.1" }
  proposal-dynamic-import { "node":"12.14.1" }

Using polyfills with `usage` option:

[/Users/finnfrotscher/code/cofenster/api.renderer/src/database/index.js] Based on your code and targets, core-js polyfills were not added.
tick
renderJob
{
  id: 'ck6v632hi0000ymszw8ytr25p',
  template: 'Subtitles',
  project: {
    id: 'ck6tmmu6c00281co1cbuoaftw',
    srtUrl: 'https://s3.eu-central-1.amazonaws.com/com.cofenster.files/main.srt',
    videoDefault: 'https://s3.eu-central-1.amazonaws.com/com.cofenster.files/SMB_Feb_V2.mp4',
    videoSubtitled: null,
    shotlists: [ [Object] ],
    __typename: 'Project'
  },
  __typename: 'RenderJob'
}
checking After Effects command line renderer patch...
command line patch already is in place
[WIu1ag6AFiAwcSgRNufFv] setting up job...
[WIu1ag6AFiAwcSgRNufFv] working directory is: /Users/finnfrotscher/code/cofenster/api.renderer/tmp/WIu1ag6AFiAwcSgRNufFv
[WIu1ag6AFiAwcSgRNufFv] downloading assets...
[WIu1ag6AFiAwcSgRNufFv] applying prerender actions...
[WIu1ag6AFiAwcSgRNufFv] running script assemble...
Step 'Rendering' has encountered Error: TypeError
render error:  TypeError: `.matchAll` does not allow non-global regexes
    at String.matchAll (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@babel/node/node_modules/core-js/modules/es.string.match-all.js:96:41)
    at EnhancedScript.findMissingMatchesInJSX (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:311:45)
    at EnhancedScript.build (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:448:14)
    at wrapEnhancedScript (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:462:27)
    at /Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:484:27
    at Array.map (<anonymous>)
    at module.exports (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/script.js:471:16)
    at module.exports (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/helpers/state.js:8:12)
    at /Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/index.js:97:22
    at runMicrotasks (<anonymous>)
lifecycle error TypeError: Cannot read property 'name' of undefined
    at Object.onError (/Users/finnfrotscher/code/cofenster/api.renderer/src/lifecycle/index.js:29:72)
    at _default (/Users/finnfrotscher/code/cofenster/api.renderer/src/lifecycle/index.js:44:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
^C

```

**Comment by FinnFrotscher** [comment]
There is no jsx file generated. I assume its an conflict with babel.

**Comment by FinnFrotscher** [comment]
Correct, the issue is related to `babel-node`. When running on plain `node`, it works. 
funnily, i use the exact same babel.config in both cases.
