### ISSUE TITLE
Couldn't find module @nexrender/provider-c, Unknown protocol provided.

### ISSUE THREAD

**Issue by pushpendrabansal** [inlife/nexrender#332]
checking After Effects command line renderer patch...
command line patch already is in place
[4BrVIPskWPjSksLWnr5ij] setting up job...
[4BrVIPskWPjSksLWnr5ij] working directory is: C:\Users\BANSAL~1\AppData\Local\Temp\2\nexrender\4BrVIPskWPjSksLWnr5ij
[4BrVIPskWPjSksLWnr5ij] downloading assets...
> job rendering failed
Error: Couldn't find module @nexrender/provider-c, Unknown protocol provided.
    at download (C:\Users\bansalpunitib\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\download.js:103:43)
    at module.exports (C:\Users\bansalpunitib\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\download.js:121:9)
    at module.exports (C:\Users\bansalpunitib\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\helpers\state.js:8:12)
    at C:\Users\bansalpunitib\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\index.js:95:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by inlife** [comment]
could you show your job definition?

**Comment by pushpendrabansal** [comment]
Command i m using -  nexrender-cli --file data.json --binary="C:/Program Files/Adobe/Adobe After Effects CS5/Support Files/aerender.exe" --skip-cleanup

data.json
`{
    "template": {
        "src": "C:/Users/bansalpunitib/Desktop/vmaker/nexrender-boilerplate/first.aep",
        "composition": "main"
    },
    "assets": [
	{
	    "src": "https://miro.medium.com/max/756/1*zgWzWOIohXtsS6ZZ7SSZkw.png",
            "type": "image",
            "layerIndex": 2
	}
    ]
}`

**Comment by inlife** [comment]
you have wrong `job.template.src` setting
it should be "file:///C:/Users/bansalpunitib/Desktop/vmaker/nexrender-boilerplate/first.aep"

**Comment by pushpendrabansal** [comment]
Its showing new error

> starting nexrender-cli
checking After Effects command line renderer patch...
command line patch already is in place
[b0JE5-FSJG1nys2UwxnK5] setting up job...
[b0JE5-FSJG1nys2UwxnK5] working directory is: C:\Users\BANSAL~1\AppData\Local\Temp\2\nexrender\b0JE5-FSJG1nys2UwxnK5
[b0JE5-FSJG1nys2UwxnK5] downloading assets...
> job rendering failed
**Error: [object Object]
    at WriteStream.errorHandler** (C:\Users\bansalpunitib\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\download.js:65:36)
    at WriteStream.emit (events.js:323:22)
    at internal/fs/streams.js:320:12
    at FSReqCallback.oncomplete (fs.js:154:23)
