### ISSUE TITLE
Pickup failed nexrender-worker-win64.exe

### ISSUE THREAD

**Issue by bdb400** [inlife/nexrender#356]
After I updated `nexrender-worker-win64.exe` and `nexrender-server-win64.exe` this error starting heppening. I don't remember the original version, but the new version is v1.12.3

```
FetchError: request to https://localhost:3000/api/v1/jobs/pickup failed, reason: write EPROTO 29020:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\pkg-fetch\precompile\node\deps\openssl\openssl\ssl\record\ssl3_record.c:332:

    at ClientRequest.<anonymous> (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\api\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:452:5)
    at onwrite (_stream_writable.js:473:5)
    at internal/streams/destroy.js:50:7
    at TLSSocket.Socket._destroy (net.js:664:5)
    at TLSSocket.destroy (internal/streams/destroy.js:38:8) {
  message: 'request to https://localhost:3000/api/v1/jobs/pickup failed, reason: write EPROTO 29020:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:c:\\pkg-fetch\\precompile\\node\\deps\\openssl\\openssl\\ssl\\record\\ssl3_record.c:332:\n',
  type: 'system',
  errno: 'EPROTO',
  code: 'EPROTO'
}
```

**Comment by bdb400** [comment]
I found the problem, I changed `https` to `http`

**Comment by inlife** [comment]
Seems like there are some issues with OpenSSL on the system.
