### ISSUE TITLE
ReferenceError: Ԫ� is undefined

### ISSUE THREAD

**Issue by Jack-Stencil** [inlife/nexrender#387]
**Describe the bug**
Using nexrender cli version 14.4 and newer causes this strange error when starting the render job.

```
[Fe-Nfvawrxrh8JEdoHt1F] applying prerender actions...
[Fe-Nfvawrxrh8JEdoHt1F] running script assemble...
[Fe-Nfvawrxrh8JEdoHt1F] rendering job...
[Fe-Nfvawrxrh8JEdoHt1F] spawning aerender process: /Applications/Adobe After Effects CC 2019/aerender -project /var/folders/3_/f_vd74w974v2qyrcdqf3x_d00000gn/T/nexrender/Fe-Nfvawrxrh8JEdoHt1F/MusicTeaserDemoTemplate_V1.aep -comp renderComp_16x9 -output /var/folders/3_/f_vd74w974v2qyrcdqf3x_d00000gn/T/nexrender/Fe-Nfvawrxrh8JEdoHt1F/result.mov -r /var/folders/3_/f_vd74w974v2qyrcdqf3x_d00000gn/T/nexrender/Fe-Nfvawrxrh8JEdoHt1F/nexrender-Fe-Nfvawrxrh8JEdoHt1F-script.jsx
[Fe-Nfvawrxrh8JEdoHt1F] rendering took ~11.471 sec.
[Fe-Nfvawrxrh8JEdoHt1F] writing aerender job log to: /var/folders/3_/f_vd74w974v2qyrcdqf3x_d00000gn/T/nexrender/aerender-Fe-Nfvawrxrh8JEdoHt1F.log
[Fe-Nfvawrxrh8JEdoHt1F] dumping aerender log:
Running Script: /var/folders/3_/f_vd74w974v2qyrcdqf3x_d00000gn/T/nexrender/Fe-Nfvawrxrh8JEdoHt1F/nexrender-Fe-Nfvawrxrh8JEdoHt1F-script.jsx
aerender ERROR: Error executing script: /var/folders/3_/f_vd74w974v2qyrcdqf3x_d00000gn/T/nexrender/Fe-Nfvawrxrh8JEdoHt1F/nexrender-Fe-Nfvawrxrh8JEdoHt1F-script.jsx
ReferenceError: Ԫ� is undefined
aerender ERROR: Runtime error in After Effects.
aerender version 16.1.2x55
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

> job rendering failed
Error: Couldn't find a result file
    at ChildProcess.<anonymous> (/snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/tasks/render.js)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at Pipe.<anonymous> (net.js:659:12)

```

Render job works fine for version 1.14.3. 

Issue seen when testing versions 1.14.4, 1.14.5, 1.14.6 and 1.15.1.

**Information about environment**
* Which version of nexrender are you using? 14.4
* What kind of the setup do you have? (server+worker or cli) Tested with CLI and Server+worker. Issue happens for both setups.
* Are you using pre-built binaries or globally installed npm packages? I tested with the binaries from the github release page as well as building the packages myself.
* Which kind (and version) of operating system you are running it in? Mac
* Any additional information that might be helpful

**Expected behavior**
Render Starts without errors.

**Comment by Jack-Stencil** [comment]
PS I tried running the cli with the flag --force-patch and sudo

**Comment by inlife** [comment]
Thank you @Jack-Stencil for including versions, you helped me to find an exact source of the issue, will push a fix soon!

**Comment by inlife** [comment]
Please, check if the release `v1.16.0` fixes that issue.

**Comment by Jack-Stencil** [comment]
@inlife Thank you very much the issue is resolved!
