### ISSUE TITLE
nexrender-server SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by nicohery** [inlife/nexrender#445]
After a nexrender-server killing and manual deleting jobs, impossible to restart :
`nexrender-server \ --port=3050 \ --secret=myapisecret`

```
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\@nexrender\server\src\helpers\database.js:14:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\@nexrender\server\src\routes\jobs-create.js:4:30)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
```
**Tried**
- Run jobs in cli-mode : OK
- Uninstall reinstall nexrender packages

**Information about environment**
Using @nexrender/server@1.18.0 + @nexrender/worker@1.18.0 
Using globally installed npm packages via npm install -g  @nexrender/cli @nexrender/server ...
Running on Windows Server 2016 Standard (hosted)

**Comment by inlife** [comment]
Seems like the file it attempts to read has an invalid json content. Try removing the file database altogether.

**Comment by nicohery** [comment]
I located an empty database file, in my user directory C:\Users\root\nexrender\database.js
By deleting it, nexrender-server restarts and a new database.js file is created (containing an empty JSON array `[]`)

Thanks a lot for your help !

I tested a tiny patch on @nexrender\server\src\helpers\database.js to prevent this error. Could I suggest it to you via a pull-request ?

**Comment by inlife** [comment]
Sure thing, pull requests are welcomed! :)
