### ISSUE TITLE
aerender ReferenceError: PREFType is undefined

### ISSUE THREAD

**Issue by crisdeb** [inlife/nexrender#471]
Hi I'm using nexrender-cli-win64.exe for windows version v1.19.2 (using pre-built binaries) with AfterEffect CS6 with a very simple job (Windows 7 pro Service pack 1)

but I get this error:

**aerender ReferenceError: PREFType is undefined
LoadLibrary "n" failed!
LoadLibrary "n" failed!**

this is the full output from cmd:

```
C:\Nexrender>nexrender-cli-win64.exe --file js
on/test_A_04.json --binary "C:\Program Files\Adobe\Adobe After Effects CS6\Suppo
rt Files\aerender.exe"
> starting nexrender-cli
checking After Effects command line renderer patch...
command line patch already is in place
[8we6aPxczUlezavGIU1WS] setting up job...
[8we6aPxczUlezavGIU1WS] working directory is: C:\Users\admin\AppData\Local\Temp\
nexrender\8we6aPxczUlezavGIU1WS
[8we6aPxczUlezavGIU1WS] downloading assets...
[8we6aPxczUlezavGIU1WS] applying prerender actions...
[8we6aPxczUlezavGIU1WS] running script assemble...
[8we6aPxczUlezavGIU1WS] rendering job...
[8we6aPxczUlezavGIU1WS] rendering took ~4.263 sec.
[8we6aPxczUlezavGIU1WS] writing aerender job log to: C:\Users\admin\AppData\Loca
l\Temp\nexrender\aerender-8we6aPxczUlezavGIU1WS.log
[8we6aPxczUlezavGIU1WS] dumping aerender log:
Using DXGI: Device: "Intel(R) HD Graphics Family" has dedicated video RAM (MB):
192 and has shared video RAM (MB): 1632 (Total: 1824 MB)
aerender version 11.0x378
Running Script: C:\Users\admin\AppData\Local\Temp\nexrender\8we6aPxczUlezavGIU1W
S\nexrender-8we6aPxczUlezavGIU1WS-script.jsx
PROGRESS: Adding specified comp to Render Queue
aerender ReferenceError: PREFType is undefined
LoadLibrary "n" failed!
LoadLibrary "n" failed!

> job rendering failed
Error: Couldn't find a result file: C:\Users\admin\AppData\Local\Temp\nexrender\
8we6aPxczUlezavGIU1WS\result.avi
    at ChildProcess.<anonymous> (C:\snapshot\nexrender\packages\nexrender-cli\no
de_modules\@nexrender\core\src\tasks\render.js)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12)

C:\Nexrender>
```

Can someone help me?

**Comment by inlife** [comment]
That does seem like some error related to the after effects itself, but I can't say what might be a reason for that. Have you tried researching this issue on other ae forums/communities? It might've been answered there already.

**Comment by crisdeb** [comment]
the problem is the version of After Effect that I use (**CS6**), downloading the trial **latest version works correctly**.
