### ISSUE TITLE
removeJob does not works from api

### ISSUE THREAD

**Issue by Fr4nZ82** [inlife/nexrender#488]
**Describe the bug**
this code...
```
...
else for (const job of rJob.jobs) {
        console.log('removing job with id:', job.jobId)
        await this.nrCient.removeJob(job.jobId)
      }
...
```
throw this error:
```
removing job with id: RddvkvtcUFiEsMk4sH8RP
(node:9604) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://localhost:3030/api/v1/jobs/RddvkvtcUFiEsMk4sH8RP reason: Unexpected end of JSON input
    at D:\inetpub\api.xxx.it\node_modules\node-fetch\lib\index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at wrappedFetch (D:\inetpub\api.xxx.it\node_modules\@nexrender\api\src\index.js:18:16)
    at Object.removeJob (D:\inetpub\api.xxx.it\node_modules\@nexrender\api\src\job.js:61:9)
    at D:\inetpub\api.xxx.it\src\services\nexrender.service.ts:346:9
(node:9604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:9604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Information about environment**
Which version of nexrender are you using? "@nexrender/api": "^1.19.2", server v1.19.2
What kind of the setup do you have? (server+worker + api)
Are you using pre-built binaries or globally installed npm packages? server and workers are prebuilt

**Comment by Fr4nZ82** [comment]
I put a console.log on the fetch module at the json() function:
```
/**
  * Decode response as json
  *
  * @return  Promise
  */
	json() {
		var _this2 = this;

		return consumeBody.call(this).then(function (buffer) {
			try {
				console.log('BUFFER TO STRING',buffer.toString()) // <- here
				return JSON.parse(buffer.toString());
			} catch (err) {
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
			}
		});
	},
```
and i see that 'BUFFER TO STRING' is logged 2 times, one with full job data, one with nothing (void string?)
here the result of the log:
```
...
BUFFER TO STRING [{"uid":"4v5nmnbHEkIjeI-tkJwel","type":"default" ...full job data... }]
BUFFER TO STRING 
FetchError: invalid json response body at http://localhost:3030/api/v1/jobs/d3IBhD_x4H03bBZJJcLR- reason: Unexpected end of JSON input
...
```
