### ISSUE TITLE
Error: Couldn't find module @nexrender/provider-c, Unknown protocol provided.

### ISSUE THREAD

**Issue by timothee-durand** [inlife/nexrender#557]
When i try to render a file, i got a strange error in the console :
`using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects CC 2019\Support Files\aerender.exe
checking After Effects command line renderer patch...
command line patch already is in place
[p5e_hUv7RAWgdsT1DHOOV] setting up job...
[p5e_hUv7RAWgdsT1DHOOV] working directory is: C:\Users\timot\AppData\Local\Temp\nexrender\p5e_hUv7RAWgdsT1DHOOV
[p5e_hUv7RAWgdsT1DHOOV] downloading assets...
Error: Couldn't find module @nexrender/provider-c, Unknown protocol provided.
    at download (C:\Users\timot\Documents\COURS\WEBTV\Génération Synthé\node_modules\@nexrender\core\src\tasks\download.js:117:43)
    at module.exports (C:\Users\timot\Documents\COURS\WEBTV\Génération Synthé\node_modules\@nexrender\core\src\tasks\download.js:135:9)
    at module.exports (C:\Users\timot\Documents\COURS\WEBTV\Génération Synthé\node_modules\@nexrender\core\src\helpers\state.js:8:12)
    at C:\Users\timot\Documents\COURS\WEBTV\Génération Synthé\node_modules\@nexrender\core\src\index.js:107:22
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async main (C:\Users\timot\Documents\COURS\WEBTV\Génération Synthé\src\assets\index.js:20:20)`

But no provider-c exist...

Here is my index.js

`
const { render } = require('@nexrender/core')

const job = {
    template: {
        src: "C:/Users/timot/Documents/COURS/WEBTV/Génération Synthé/SYNTHES_WEBTV.aep",
        composition: "SYNTHE_WEBTV"
    },
    actions: {
        postrender: [{
            module: "@nexrender/action-encode",
            output: "synthe.mp4",
            preset: "mp4"
        }]
    }
};

const projet = {
    template: {
        src: `.\SYNTHES_WEBTV.aep`,
        composition: "SYNTHE_WEBTV"
    },
    actions: {
        postrender: [{
                module: "@nexrender/action-encode",
                output: "output.mp4",
                preset: "mp4",
            },
            {
                module: "@nexrender/action-copy",
                input: "output.mp4",
                output: process.cwd() + "/results/output.mp4",
            },
        ],
    }
};

const main = async() => {
    const result = await render(projet)
}

main().catch(console.error);
`

**Comment by timothee-durand** [comment]
ok it's my fault in windows you must past a URI and not a path...
