### ISSUE TITLE
aerender ERROR: No comp was found with the given name.

### ISSUE THREAD

**Issue by cpienovi** [inlife/nexrender#600]
Hi! First of all I want to congratulate you for such an awesome tool.

I'm having a hard time making it work on macOS. I've tried with different .aep files and the simplest config but it always throws `aerender ERROR: No comp was found with the given name.` I've also changed comp names to lowercase and no whitespaces.

The command I'm executing is `nexrender-cli-macos --file main.json --debug` and the output is

```
starting nexrender-cli
using automatically determined directory of After Effects installation:
 - /Applications/Adobe After Effects 2021/aerender
checking After Effects command line renderer patch...
command line patch already is in place
[G2yZ5mgP8NrhlX3_zozo4] setting up job...
[G2yZ5mgP8NrhlX3_zozo4] working directory is: /var/folders/sq/h5rhprc528n943z1_vhhdlxc0000gn/T/nexrender/G2yZ5mgP8NrhlX3_zozo4
[G2yZ5mgP8NrhlX3_zozo4] downloading assets...
[G2yZ5mgP8NrhlX3_zozo4] applying prerender actions...
[G2yZ5mgP8NrhlX3_zozo4] running script assemble...
[G2yZ5mgP8NrhlX3_zozo4] rendering job...
[G2yZ5mgP8NrhlX3_zozo4] spawning aerender process: /Applications/Adobe After Effects 2021/aerender -project /var/folders/sq/h5rhprc528n943z1_vhhdlxc0000gn/T/nexrender/G2yZ5mgP8NrhlX3_zozo4/test_1.aep -comp main -output /var/folders/sq/h5rhprc528n943z1_vhhdlxc0000gn/T/nexrender/G2yZ5mgP8NrhlX3_zozo4/result.mov -r /var/folders/sq/h5rhprc528n943z1_vhhdlxc0000gn/T/nexrender/G2yZ5mgP8NrhlX3_zozo4/nexrender-G2yZ5mgP8NrhlX3_zozo4-script.jsx
Running Script: /var/folders/sq/h5rhprc528n943z1_vhhdlxc0000gn/T/nexrender/G2yZ5mgP8NrhlX3_zozo4/nexrender-G2yZ5mgP8NrhlX3_zozo4-script.jsx

aerender ERROR: No comp was found with the given name.

aerender version 18.1x38
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

[G2yZ5mgP8NrhlX3_zozo4] rendering took ~15.689 sec.
[G2yZ5mgP8NrhlX3_zozo4] writing aerender job log to: /var/folders/sq/h5rhprc528n943z1_vhhdlxc0000gn/T/nexrender/aerender-G2yZ5mgP8NrhlX3_zozo4.log
[G2yZ5mgP8NrhlX3_zozo4] dumping aerender log:
Running Script: /var/folders/sq/h5rhprc528n943z1_vhhdlxc0000gn/T/nexrender/G2yZ5mgP8NrhlX3_zozo4/nexrender-G2yZ5mgP8NrhlX3_zozo4-script.jsx
aerender ERROR: No comp was found with the given name.
aerender version 18.1x38
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

> job rendering failed
Error: Couldn't find a result file: /var/folders/sq/h5rhprc528n943z1_vhhdlxc0000gn/T/nexrender/G2yZ5mgP8NrhlX3_zozo4/result.mov
    at ChildProcess.<anonymous> (/snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/tasks/render.js)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12)
```

OS: macOS Big Sur v11.2.3
Adobe After Effects v18.1.0 (Build 38)
nexrender-cli-macos v1.28.1 

Is there something I'm missing? Thanks in advance!

Edit:
Forgot to add json file
```
{
    "template": {
        "src": "file:///Users/carlospienovi/Desktop/after_effects/test_1.aep",
        "composition": "main"
    }
}
```

**Comment by cpienovi** [comment]
I was able to fix this by thanks to https://github.com/inlife/nexrender/issues/602#issuecomment-843766144
