### ISSUE TITLE
aerender ERROR: No comp was found with the given name. LoadLibrary "n" failed! LoadLibrary "n" failed!

### ISSUE THREAD

**Issue by 2294258095** [inlife/nexrender#602]
> starting nexrender-cli
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects CC 2019\Support Files\aerender.exe
checking After Effects command line renderer patch...
command line patch already is in place
[1cKE7bXW6K2uuP6GzZxBB] setting up job...
[1cKE7bXW6K2uuP6GzZxBB] working directory is: C:\Users\gyp\AppData\Local\Temp\nexrender\1cKE7bXW6K2uuP6GzZxBB
[1cKE7bXW6K2uuP6GzZxBB] downloading assets...
[1cKE7bXW6K2uuP6GzZxBB] applying prerender actions...
[1cKE7bXW6K2uuP6GzZxBB] running script assemble...
[1cKE7bXW6K2uuP6GzZxBB] rendering job...
[1cKE7bXW6K2uuP6GzZxBB] rendering took ~4.982 sec.
[1cKE7bXW6K2uuP6GzZxBB] writing aerender job log to: C:\Users\gyp\AppData\Local\Temp\nexrender\aerender-1cKE7bXW6K2uuP6GzZxBB.log
[1cKE7bXW6K2uuP6GzZxBB] dumping aerender log:
Using DXGI: Device: "Intel(R) UHD Graphics 630" has dedicated video RAM (MB): 128 and has shared video RAM (MB): 8125 (Total: 8253 MB)
Unable to read VR Path Registry from C:\Users\gyp\AppData\Local\openvr\openvrpaths.vrpath
aerender version 16.1.2x55
Running Script: C:\Users\gyp\AppData\Local\Temp\nexrender\1cKE7bXW6K2uuP6GzZxBB\nexrender-1cKE7bXW6K2uuP6GzZxBB-script.jsx
aerender ERROR: No comp was found with the given name.
LoadLibrary "n" failed!
LoadLibrary "n" failed!

> job rendering failed
Error: Couldn't find a result file: C:\Users\gyp\AppData\Local\Temp\nexrender\1cKE7bXW6K2uuP6GzZxBB\result.avi
    at ChildProcess.<anonymous> (C:\Users\gyp\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\render.js:174:31)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    
    
    AE 2019  v16.1.2.55
    Win10 20H2

**Comment by inlife** [comment]
The main error message here is: `No comp was found with the given name.`
Please make sure you've configured everything correctly

**Comment by cpienovi** [comment]
I'm facing the same `No comp was found with the given name.` issue and I can't figure out what I'm doing wrong. What do you need to tell? Thanks!

**Comment by 2294258095** [comment]
I found the reason, because of the composite name
