### ISSUE TITLE
Postrender input attribute is ignored

### ISSUE THREAD

**Issue by estevopaz** [inlife/nexrender#622]
{
        "template": {
            "src": "file:///Z:/6251/ae_templates/714/714_2393.aepx",
            "composition": "Standard"
        },
        "actions": {
            "postrender": [
                {
                    "module": "@nexrender/action-encode",
                    "preset": "mp4",
                    "input": "result.mov",
                    "output": "encoded.mp4",
                    "params": {
                        "-pix_fmt": "yuv420p",
                        "-r": "30.00"
                    }
                },
                {
                    "module": "@nexrender/action-copy",
                    "input": "encoded.mp4",
                    "output": "Z:/results/6251_fb_30s_camp2393_190821.mp4"
               }
           ]
        },
        ...

Worker output:

    [Ajl83rUi4hcyygq_Q_-fz] error occurred: Error: Couldn't find a result file: C:\Users\Admin\AppData\Local\Temp\nexrender\Ajl83rUi4hcyygq_Q_-fz\result.avi
        at ChildProcess.<anonymous> (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\render.js)
        at ChildProcess.emit (events.js:311:20)
        at maybeClose (internal/child_process.js:1021:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    
You can see the input is set to "result.mov" and the worker search for "result.avi" (default one I guess).

Server: v1.28.1 in Debian
Worker: v1.28.1 in Win10

Thanks a lot for the project, best,
Estevo.

**Comment by estevopaz** [comment]
Double checking the versions, I found what it probably a igsignificant mistake:

    PS Z:\Utilities> .\nexrender-worker-win64_1.28.1.exe --version
    1.28.0

**Comment by estevopaz** [comment]
I found the problem, in new versions, attribute outputExt must be set:

    'template': {
        ...
        'outputExt': 'mov'
    },
    
Feel free to close the issue if you consider it ;)
