### ISSUE TITLE
Worker With private ssl cert 

### ISSUE THREAD

**Issue by mari0theminer** [inlife/nexrender#636]
Hi, i am trying out your awesome tool.

Sadly, I have the problem that my  Worker cant connect to my Server.
The Reason is simple, I use a Custom certificate, so the worker won't connect 

``` .\nexrender-worker.exe : FetchError: request to https://nex_server-test.int/api/v1/jobs/pickup failed, reason: self signed 
certificate in certificate chain
At C:\Users\me\Desktop\windows-scripts\RunWorker.ps1:2 char:2
+  .\nexrender-worker.exe  --host=https://nex_server-test.int ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (FetchError: req...rtificate chain:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    at ClientRequest.<anonymous> 
(C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\api\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to https://nex_server-test.apps.int/api/v1/jobs/pickup failed, reason: self signed certificate in 
certificate chain',
  type: 'system',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
} 
```
I tried adding the root certificate in windows but it didn't helped :(
is there a way to give the work a valid certificate or disable this check?

**Comment by shahabbasi** [comment]
You can use [let's encrypt](https://letsencrypt.org/) to get a valid cert, however this error is happening in `node-fetch library` http call and is not about nexrender.

**Comment by mari0theminer** [comment]
I am in an internal network with its own certs, so this is not an option but thx
