### ISSUE TITLE
nexrender doesn't find the binary

### ISSUE THREAD

**Issue by Digiperf** [inlife/nexrender#666]
Hye

Since I switched to After Effects 2022, nex-render-cli doesn't work anymore: 

```
$ nexrender-cli --file F:/Users/YvesDenan/Desktop/paramsGenerationVideo.json --debug
> starting nexrender-cli
C:\Users\rudy\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\index.js:51
        throw new Error('you should provide a proper path to After Effects\' \"aerender\" binary')
        ^

Error: you should provide a proper path to After Effects' "aerender" binary
    at init (C:\Users\rudy\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\index.js:51:15)
    at Object.<anonymous> (C:\Users\rudy\AppData\Roaming\npm\node_modules\@nexrender\cli\src\bin.js:218:12)
```
`AE v22.0.1`
`nexrender-cli -v => 1.31.0`

thanks

**Comment by Digiperf** [comment]
OK I updated to 1.33 it's now OK
Sorry for nose
