### ISSUE TITLE
Why can't I use parameters?

### ISSUE THREAD

**Issue by ujlm** [inlife/nexrender#680]
Can someone help me to include parameters in my JSX script?
I'm trying to use parameters with my JSX script, but I always get this error (however, I don't use the parameter "t"?):

`PS C:\Users\user\Documents\Coding\nextest\nexrender_test\nextest> .\nexrender-cli-win64.exe --file nextest.json --binary="C:/Program Files/Adobe/Adobe After Effects 2021/Support Files/aerender.exe"
> starting nexrender-cli
checking After Effects command line renderer patch...
command line patch already is in place
out-of-date version of the commandLineRenderer.jsx patch is detected, attepmting to update
[QB9K0Ptik1avhZxOBVbyx] setting up job...
[QB9K0Ptik1avhZxOBVbyx] working directory is: C:\Users\user\AppData\Local\Temp\nexrender\QB9K0Ptik1avhZxOBVbyx
[QB9K0Ptik1avhZxOBVbyx] applying predownload actions...
[QB9K0Ptik1avhZxOBVbyx] downloading assets...
[QB9K0Ptik1avhZxOBVbyx] applying postdownload actions...
[QB9K0Ptik1avhZxOBVbyx] applying prerender actions...
[QB9K0Ptik1avhZxOBVbyx] running script assemble...
[QB9K0Ptik1avhZxOBVbyx]  -- W A R N I N G --
        The following parameters used in the script were NOT found on the JSON "parameters" object of your script asset file:///C:/Users/user/Documents/Coding/nextest/nexrender_test/nextest/scripts/test2.jsx

            t

        Please set defaults in your JSX script (see documentation) or copy the following placeholder JSON code snippet and replace the values with your own:

            "parameters" : [

                {
                    "key" : "t",
                    "value" : null
                }

            ]

        Remember to always use a fallback default value for any use of the NX object to have the ability to run this script on After Effects directly.
        Example:
            const dogName = NX && NX.get("doggo") || "Doggo";

[QB9K0Ptik1avhZxOBVbyx] rendering job...
[QB9K0Ptik1avhZxOBVbyx] rendering reached an error: Error executing script: C:\Users\user\AppData\Local\Temp\nexrender\QB9K0Ptik1avhZxOBVbyx\nexrender-QB9K0Ptik1avhZxOBVbyx-script.jsx

[QB9K0Ptik1avhZxOBVbyx] rendering took ~8.244 sec.
[QB9K0Ptik1avhZxOBVbyx] writing aerender job log to: C:\Users\user\AppData\Local\Temp\nexrender\aerender-QB9K0Ptik1avhZxOBVbyx.log
[QB9K0Ptik1avhZxOBVbyx] dumping aerender log:
aerender version 18.2.1x8
Using DXGI: Device: "NVIDIA GeForce GTX 1650 with Max-Q Design" has dedicated video RAM (MB): 3962
    name                                    : NVIDIA GeForce GTX 1650 with Max-Q Design
    VendorId                                : 4318
    DeviceId                                : 8081
    SubSysId                                : 580851626
    Revision                                : 161
    DedicatedVideoMemory                    : 4154458112
    DedicatedSystemMemory                   : 0
    SharedSystemMemory                      : 8450797568
    MemoryBudget                            : 3531289396
    AdapterLuid.LowPart                     : 77694
    AdapterLuid.HighPart                    : 0
    Flags                                   : 0
        DoublePrecisionFloatShaderOps           : yes
        ConservativeRasterizationTier           : 3
        CrossNodeSharingTier                    : 0
        ResourceBindingTier                     : 3
        ResourceHeapTier                        : 2
        TiledResourcesTier                      : 3
        NodeIndex                               : 0
        TileBasedRenderer                       : no
        UMA                                     : no
        CacheCoherentUMA                        : no
        feature level                           : 0x00009100
        feature level                           : 0x00009200
        feature level                           : 0x00009300
        feature level                           : 0x0000a000
        feature level                           : 0x0000a100
        feature level                           : 0x0000b000
        feature level                           : 0x0000b100
        feature level                           : 0x0000c000
        feature level                           : 0x0000c100
        MaxSupportedFeatureLevel                : 0x0000c100
        HighestShaderModel                      : 0x60
        WaveOps                                 : yes
        WaveLaneCountMin                        : 32
        WaveLaneCountMax                        : 32
        TotalLaneCount                          : 1024
        ExpandedComputeResourceStates           : yes
        Int64ShaderOps                          : yes
        RootSignature.HighestVersion            : 0x2
    name                                    : Intel(R) UHD Graphics 630
    VendorId                                : 32902
    DeviceId                                : 16027
    SubSysId                                : 580851626
    Revision                                : 0
    DedicatedVideoMemory                    : 134217728
    DedicatedSystemMemory                   : 0
    SharedSystemMemory                      : 8450797568
    MemoryBudget                            : 7759822234
    AdapterLuid.LowPart                     : 76788
    AdapterLuid.HighPart                    : 0
    Flags                                   : 0
        DoublePrecisionFloatShaderOps           : yes
        ConservativeRasterizationTier           : 3
        CrossNodeSharingTier                    : 0
        ResourceBindingTier                     : 3
        ResourceHeapTier                        : 2
        TiledResourcesTier                      : 3
        NodeIndex                               : 0
        TileBasedRenderer                       : no
        UMA                                     : yes
        CacheCoherentUMA                        : yes
        feature level                           : 0x00009100
        feature level                           : 0x00009200
        feature level                           : 0x00009300
        feature level                           : 0x0000a000
        feature level                           : 0x0000a100
        feature level                           : 0x0000b000
        feature level                           : 0x0000b100
        feature level                           : 0x0000c000
        feature level                           : 0x0000c100
        MaxSupportedFeatureLevel                : 0x0000c100
        HighestShaderModel                      : 0x60
        WaveOps                                 : yes
        WaveLaneCountMin                        : 16
        WaveLaneCountMax                        : 16
        TotalLaneCount                          : 384
        ExpandedComputeResourceStates           : yes
        Int64ShaderOps                          : yes
        RootSignature.HighestVersion            : 0x2
    Intel-specific info:
        Architecture                            : Coffeelake
        EU Count                                : 24
        Package TDP                             : 45
        Max Fill Rate (pixels/clock)            : 8
        Max Frequency                           : 1150
        Min Frequency                           : 350
Qt: Untested Windows version 10.0 detected!
Running Script: C:\Users\user\AppData\Local\Temp\nexrender\QB9K0Ptik1avhZxOBVbyx\nexrender-QB9K0Ptik1avhZxOBVbyx-script.jsx
aerender ERROR: Error executing script: C:\Users\user\AppData\Local\Temp\nexrender\QB9K0Ptik1avhZxOBVbyx\nexrender-QB9K0Ptik1avhZxOBVbyx-script.jsx
TypeError: null is not an object
aerender ERROR: Runtime error in After Effects.
Dx Device Shutdown: Intel(R) UHD Graphics 630
Dx Device Shutdown: NVIDIA GeForce GTX 1650 with Max-Q Design

> job rendering failed
Error: Couldn't find a result file: C:\Users\user\AppData\Local\Temp\nexrender\QB9K0Ptik1avhZxOBVbyx\result.avi
    at ChildProcess.<anonymous> (C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\render.js)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
PS C:\Users\user\Documents\Coding\nextest\nexrender_test\nextest>`

My main.json file looks like this:
`{
    "template": {
        "src": "file:///C:/Users/user/Documents/Coding/nextest/nexrender_test/nextest/nextest.aep",
        "composition": "MAIN"
    },
    "assets": [
        {
            "src": "file:///C:/Users/user/Documents/Coding/nextest/nexrender_test/nextest/scripts/test2.jsx",
            "type": "script",
            "parameters": [
                {
                    "type": "string",
                    "key" : "doggo",
                    "value": "woof"
                }
              ]
    }
    ],
    "actions":{
        "postrender": [
            {
                "module": "@nexrender/action-encode",
                "preset": "mp4",
                "output": "encoded.mp4",
                "params": {"-vcodec": "libx264", "-r": 25}
            },
            {
                "module": "@nexrender/action-copy",
                "input":  "encoded.mp4",
                "output": "C:/Users/user/Documents/Coding/nextest/nexrender_test/nextest/results/result_1641467500846.mp4"
            }
        ]
    }
}`

And finally, the JSX file:
`var myComp = app.project.activeItem;
var text1 = myComp.layer("vartext");
var dog = NX.get("dog") || "doggo";
text1.sourceText.setValue(dog);`

**Comment by ujlm** [comment]
Apparently, a "t" parameter should be added as well in order for it to work.
So just add
`                {
                    "key": "t",
                    "value": null
                }`
