### ISSUE TITLE
action-upload error

### ISSUE THREAD

**Issue by pulsedemon** [inlife/nexrender#720]
I'm trying to upload to s3, but I keep getting an error and I'm not sure if this is a bug or I'm doing something wrong.  Upload works fine when I use aws cli.  I have credentials exported in ~/.zshrc

This is what the worker logs:
```
[S2dDVVBqS3k1GDalJWGtK] rendering progress 1%...
[S2dDVVBqS3k1GDalJWGtK] rendering progress 100%...
[S2dDVVBqS3k1GDalJWGtK] rendering took ~28.244 sec.
[S2dDVVBqS3k1GDalJWGtK] writing aerender job log to: /var/folders/5k/y5002v3s13v36k90ygz14f4w0000gn/T/nexrender/aerender-S2dDVVBqS3k1GDalJWGtK.log
[S2dDVVBqS3k1GDalJWGtK] applying postrender actions...
[S2dDVVBqS3k1GDalJWGtK] starting action-upload action
[S2dDVVBqS3k1GDalJWGtK] action-upload: input file /var/folders/5k/y5002v3s13v36k90ygz14f4w0000gn/T/nexrender/S2dDVVBqS3k1GDalJWGtK/result.mov
[S2dDVVBqS3k1GDalJWGtK] action-upload: output file https://s3-us-east-1.amazonaws.com/bucket-name/file-name.mov
[S2dDVVBqS3k1GDalJWGtK] cleaning up...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: rimraf: missing path
    at rimraf (/opt/homebrew/lib/node_modules/@nexrender/worker/node_modules/rimraf/rimraf.js:54:3)
    at /opt/homebrew/lib/node_modules/@nexrender/worker/node_modules/@nexrender/core/src/tasks/cleanup.js:15:9
    at new Promise (<anonymous>)
    at module.exports (/opt/homebrew/lib/node_modules/@nexrender/worker/node_modules/@nexrender/core/src/tasks/cleanup.js:12:12)
    at module.exports (/opt/homebrew/lib/node_modules/@nexrender/worker/node_modules/@nexrender/core/src/helpers/state.js:8:12)
    at /opt/homebrew/lib/node_modules/@nexrender/worker/node_modules/@nexrender/core/src/index.js:122:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (/opt/homebrew/lib/node_modules/@nexrender/worker/src/index.js:77:19) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

This is my actions json:
```
"actions": {
    "postrender": [
        {
        "module": "@nexrender/action-upload",
        "provider": "s3",
        "params": {
            "region": "us-east-1",
            "bucket": "bucket-name",
            "key": "file-name.mov",
            "acl": "public-read"
        }
        }
    ]
}
```

package list:
```
npm -g list
/opt/homebrew/lib
├── @nexrender/action-copy@1.38.0
├── @nexrender/action-upload@1.38.0
├── @nexrender/cli@1.39.0
├── @nexrender/provider-s3@1.39.0
├── @nexrender/server@1.38.0
├── @nexrender/worker@1.39.0
└── npm@8.5.2
```

Any idea what's going on?

**Comment by nicohery** [comment]
I had the same error and I just tried to log "job.workpath" in /usr/local/lib/node_modules/@nexrender/worker/node_modules/@nexrender/core/src/tasks/cleanup.js 
This property was undefined. When I change "job.workpath" with "settings.workpath" it works fine but this patch is not permanent.

**Comment by pulsedemon** [comment]
Thanks for the response @nicohery.  I decided that I didn't want to configure acls on my bucket, so I don't think the upload action would work for me anyway.  Since aws cli does work, I made my own action that can run shell commands: https://www.npmjs.com/package/nexrender-action-run-command
