### ISSUE TITLE
Stack on rendering job...

### ISSUE THREAD

**Issue by nivnoiman** [inlife/nexrender#797]
Hi,
Just installed the cli and the npm package on my Windows 10 64B machine.

Tried already 3 custom aep files and got the same situation in all.

I tried to render via the cli or the npm module but still stack on the proccess.

for example this is my js code :

```
const { render } = require('@nexrender/core')

const main = async () => {
    const result = await render({
			"template": {
					"src": "file:///D:/Internet/AfterEffect/myproject.aep",
					"composition": "main"
			},
			"assets": [
				{
					"type": "data",
					"layerName": "clean",
					"property": 'Source Text',
					"value": "Niv"
				}
			],
			"actions":{
				"postrender": [
						{
								"module": "@nexrender/action-encode",
								"preset": "mp4",
								"output": "encoded.mp4"
						},
						{
								"module": "@nexrender/action-copy",
								"input": "encoded.mp4",
								"output": "D:/Internet/AfterEffect/myresult.mp4"
						}
				]
			}
		}
		)
}

main().catch(console.error);
```

the result ( more the hour ) is always the same (tmp directory change ofcourse ).

using automatically determined directory of After Effects installation:

```
C:\Program Files\Adobe\Adobe After Effects 2023\Support Files\aerender.exe
checking After Effects command line renderer patch...
command line patch already is in place
[GwibjdUSCvk2F0G9kdI4L] setting up job...
[GwibjdUSCvk2F0G9kdI4L] working directory is: C:\Users\NIV'SP~1\AppData\Local\Temp\nexrender\GwibjdUSCvk2F0G9kdI4L
[GwibjdUSCvk2F0G9kdI4L] applying predownload actions...
[GwibjdUSCvk2F0G9kdI4L] downloading assets...
[GwibjdUSCvk2F0G9kdI4L] applying postdownload actions...
[GwibjdUSCvk2F0G9kdI4L] applying prerender actions...
[GwibjdUSCvk2F0G9kdI4L] running script assemble...
[GwibjdUSCvk2F0G9kdI4L] rendering job...
```

Anyone ? :)

Thanks !

**Comment by nivnoiman** [comment]
I just change the version from 23 to 22 and now looks like it kind of get any progress. but still.

now I get this error.

```
using automatically determined directory of After Effects installation:
 - C:\Program Files\Adobe\Adobe After Effects 2022\Support Files\aerender.exe
checking After Effects command line renderer patch...
command line patch already is in place
[hufIpXD2xBE-K52I10a8V] setting up job...
[hufIpXD2xBE-K52I10a8V] working directory is: C:\Users\NIV'SP~1\AppData\Local\Temp\nexrender\hufIpXD2xBE-K52I10a8V
[hufIpXD2xBE-K52I10a8V] applying predownload actions...
[hufIpXD2xBE-K52I10a8V] downloading assets...
[hufIpXD2xBE-K52I10a8V] applying postdownload actions...
[hufIpXD2xBE-K52I10a8V] applying prerender actions...
[hufIpXD2xBE-K52I10a8V] running script assemble...
[hufIpXD2xBE-K52I10a8V] rendering job...
[hufIpXD2xBE-K52I10a8V] rendering took ~6.15 sec.
[hufIpXD2xBE-K52I10a8V] writing aerender job log to: C:\Users\NIV'SP~1\AppData\Local\Temp\nexrender\aerender-hufIpXD2xBE-K52I10a8V.log
[hufIpXD2xBE-K52I10a8V] dumping aerender log:
aerender version 22.0x111
Using DXGI: Device: "NVIDIA GeForce GTX 1050 Ti" has dedicated video RAM (MB): 4018
InitializeFileLogging failed
*** GPU Warning: GPU3 failed (previous) sanity test ***
Qt: Untested Windows version 10.0 detected!
Unable to execute script at line 1. Expected: )

[undefined] cleaning up...
Error: Couldn't find a result file: C:\Users\NIV'SP~1\AppData\Local\Temp\nexrender\hufIpXD2xBE-K52I10a8V\result.avi
    at ChildProcess.<anonymous> (D:\Internet\AfterEffect\node_modules\@nexrender\core\src\tasks\render.js:201:31)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[undefined] Temporary AfterEffects project deleted. If you want to inspect it for debugging, use "--skip-cleanup"
```

**Comment by nivnoiman** [comment]
I found solution :)
Thanks anyway.

If others also have my problem -

Version 23 did not work for me on Windows 10 64bit
I downgraded to version 22.

After that, I had to change the path of the `workpath` because I had characters in the name of my user that the software did not know how to deal with.

Have Fun !

**Comment by njho** [comment]
@nivnoiman haven't run into the issue yet, but it's likely because a dialog opens when opening .aep files created older than v23.

v23 requires .aep files older than v23 to be updated/upgraded it appears

**Comment by mgreca** [comment]
@njho That is happening to me. Do you have an idea if that dialog can be closed with some settings?
