### ISSUE TITLE
Nexrender throws exception after failed render.

### ISSUE THREAD

**Issue by Tillaert** [inlife/nexrender#814]
**Describe the bug**
When a render is failed, the cleanup fails. Because the `job.uid` is `undefined`.

```
[B-giiV1TVSy6lXvKSw2JZ] dumping aerender log:
aerender version 23.0x59
PROGRESS: Launching After Effects...
WARNING:After Effects warning: Project has missing fonts.
.......
aerender ERROR: Runtime error in After Effects.

[undefined] cleaning up...
Error: Couldn't find a result file: C:\Users\Administrator\AppData\Local\Temp\nexrender\B-giiV1TVSy6lXvKSw2JZ\result.avi
    at ChildProcess.<anonymous> (C:\renderer-master\node_modules\@nexrender\core\src\tasks\render.js:208:31)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:313:12)
SendResult a869e195-892f-40ed-9617-bb49fe6cfcf4 failed Couldn't find a result file: C:\Users\ContainerAdministrator\AppData\Local\Temp\nexrender\B-giiV1TVSy6lXvKSw2JZ\result.avi undefined
node:internal/errors:484
    ErrorCaptureStackTrace(err);

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:429:7)
    at C:\renderer-master\node_modules\@nexrender\core\src\tasks\cleanup.js:18:33
    at new Promise (<anonymous>)
    at module.exports (C:\renderer-master\node_modules\@nexrender\core\src\tasks\cleanup.js:13:12)
    at module.exports (C:\renderer-master\node_modules\@nexrender\core\src\helpers\state.js:8:12)
    at C:\renderer-master\node_modules\@nexrender\core\src\index.js:122:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///C:/renderer-master/index.js:126:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Information about environment**
* Nexrenderer v1.40.0
* Windows Server 2019

**Expected behavior**
Cleanup should receive correct UID, or cleanup should exit without error.

**Comment by Tillaert** [comment]
I also see that the UID is `undefined` whenever an exception is handled, this prevents proper cleanup. I think this is due to the fact that the job object is recreated in the `startup` task. The exception handler get the original `job` object (not the one that's propagated in the `promise->then` chain, which does not have a `uid` set. 

The fix would be to take the object creation out of the `startup` task and create the object in the `core` index.js.
