### ISSUE TITLE
Output file not found: result.avi

### ISSUE THREAD

**Issue by APZmedia** [inlife/nexrender#868]
I'm running the first test using a command line:

` nexrender-cli --file example.json --workpath 'C:\CODING\GSheet2AE\gsheets2ae\WS\'`

and I'm getting the following error:

```
[dJCCVSifvBDFHkBPMUQn2] setting up job...                                                                                                              [dJCCVSifvBDFHkBPMUQn2] working directory is: C:\CODING\GSheet2AE\gsheets2ae\WS\dJCCVSifvBDFHkBPMUQn2                                                  [dJCCVSifvBDFHkBPMUQn2] applying predownload actions...                                                                                                [dJCCVSifvBDFHkBPMUQn2] downloading assets...                                                                                                          [dJCCVSifvBDFHkBPMUQn2] applying postdownload actions...                                                                                               [dJCCVSifvBDFHkBPMUQn2] applying prerender actions...                                                                                                  [dJCCVSifvBDFHkBPMUQn2] running script assemble...                                                                                                     [dJCCVSifvBDFHkBPMUQn2] rendering job...                                                                                                               [dJCCVSifvBDFHkBPMUQn2] rendering took ~9.594 sec.                                                                                                     [dJCCVSifvBDFHkBPMUQn2] writing aerender job log to: C:\CODING\GSheet2AE\gsheets2ae\WS\aerender-dJCCVSifvBDFHkBPMUQn2.log                              [dJCCVSifvBDFHkBPMUQn2] cleaning up...                                                                                                                 > job rendering failed                                                                                                                                 Error: Output file not found: C:\CODING\GSheet2AE\gsheets2ae\WS\dJCCVSifvBDFHkBPMUQn2\result.avi                                                           at ChildProcess.<anonymous> (C:\nodejs\nvm\v14.21.2\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\render.js:223:31)               at ChildProcess.emit (events.js:400:28)                                                                                                                at maybeClose (internal/child_process.js:1088:16)                                                                                                      at Socket.<anonymous> (internal/child_process.js:446:11)                                                                                               at Socket.emit (events.js:400:28)                                                                                                                      at Pipe.<anonymous> (net.js:686:12)                                                                                                                [dJCCVSifvBDFHkBPMUQn2] Temporary AfterEffects project deleted. If you want to inspect it for debugging, use "--skip-cleanup"                          ```
What shall I do? There's no reference to a "result.avi" anywhere. Shall I specify an output path somewhere?

**Comment by limzykenneth** [comment]
Usually when it says result.avi not found it means that AE was not able to complete the render successfully. Do check that your composition is able to be rendered from AE itself and sharing the job JSON file will help us debug your problem easier.
