### ISSUE TITLE
Alpha testing thread for nexrender binaries

### ISSUE THREAD

**Issue by HarryLafranc** [inlife/nexrender#91]
Hello,

Thanks for making this project, it's so helpful !

I saw you published v1.0 alpha and decided to try it, but when I want to launch either nexrender-worker or nexrender-server bin, it crashes. 

Here are the logs I got : 

```
./nexrender-server-macos

pkg/prelude/bootstrap.js:1178
      throw error;
      ^

Error: Cannot find module 'arg'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snapshot/nexrender-server/src/bin.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
```
^ I had this one on macOS and on Windows. ^

```
./nexrender-worker-macos

> starting nexrender-worker endpoint http://localhost:3000; using secret: no
using automatically determined directory of After Effects installation:
 - /Applications/Adobe After Effects CC 2019/aerender
adding default render-only-node license for After Effects at:
 - /Users/guillaume/Documents/Adobe/ae_render_only_node.txt
checking After Effects command line renderer patch...
backing up original command line script to:
 - /Applications/Adobe After Effects CC 2019/Backup.Scripts/Startup/commandLineRenderer.jsx
patching the command line script
(node:9927) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/Applications/Adobe After Effects CC 2019/Scripts/Startup/commandLineRenderer.jsx'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:483:32)
    at Object.fs.writeFileSync (fs.js:1309:33)
    at writeTo (/snapshot/nexrender/packages/nexrender-worker/node_modules/@nexrender/core/src/helpers/patch.js:0:0)
    at module.exports (/snapshot/nexrender/packages/nexrender-worker/node_modules/@nexrender/core/src/helpers/patch.js:0:0)
    at init (/snapshot/nexrender/packages/nexrender-worker/node_modules/@nexrender/core/src/index.js:0:0)
    at start (/snapshot/nexrender/packages/nexrender-worker/src/index.js:0:0)
    at Object.<anonymous> (/snapshot/nexrender/packages/nexrender-worker/src/bin.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
(node:9927) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9927) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Did I miss something or is it a bug ? 
Thanks !

**Comment by HarryLafranc** [comment]
Thanks for your reply !

All right, it's an alpha after all :) 
For the second one, I don't know if a chmod to the current user could broke something on the AE side ? After a chmod the bin is launching normally, but I don't know if AE will be happy with it.

**Comment by inlife** [comment]
chmod is actually a good idea, probably wont work on windows tho

**Comment by HarryLafranc** [comment]
Oops, I mixed up chmod and chown... I meant chown. I tried to chown the file to myself and worked on my computer at work. It worked too on my personal computer but now I have this error (for the worker) : 

```
./nexrender-worker-macos --host=http://localhost:8000

> starting nexrender-worker endpoint prout; using secret: yes
using automatically determined directory of After Effects installation:
 - /Applications/Adobe After Effects CC 2018/aerender
adding default render-only-node license for After Effects at:
 - /Users/harrylafranc/Documents/Adobe/ae_render_only_node.txt
checking After Effects command line renderer patch...
backing up original command line script to:
 - /Applications/Adobe After Effects CC 2018/Backup.Scripts/Startup/commandLineRenderer.jsx
patching the command line script
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/snapshot/nexrender/packages/nexrender-worker/node_modules/@nexrender/api/node_modules/node-fetch/lib/index.js:1293:9)
    at fetch.isRedirect (/snapshot/nexrender/packages/nexrender-worker/node_modules/@nexrender/api/node_modules/node-fetch/lib/index.js:1393:19)
    at new Promise (<anonymous>)
    at fetch (/snapshot/nexrender/packages/nexrender-worker/node_modules/@nexrender/api/node_modules/node-fetch/lib/index.js:1390:9)
    at wrappedFetch (/snapshot/nexrender/packages/nexrender-worker/node_modules/@nexrender/api/src/index.js:0:0)
    at Object.listJobs (/snapshot/nexrender/packages/nexrender-worker/node_modules/@nexrender/api/src/job.js:0:0)
    at nextJob (/snapshot/nexrender/packages/nexrender-worker/src/index.js:0:0)
    at start (/snapshot/nexrender/packages/nexrender-worker/src/index.js:0:0)
    at Object.<anonymous> (/snapshot/nexrender/packages/nexrender-worker/src/bin.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
```

However, the server seems to work fine ! Thanks for the fix :)

**Comment by inlife** [comment]
well something went wrong with host url parameter
it shouldn't say "endpoint prout;", and as far as i see form command line you are not using secret
seems like it got corrupted somehow
i just tested it locally, everything seems to work fine

could you please try to `$ crc32 nexrender-worker-macos`, maybe the binary didn't download properly

**Comment by HarryLafranc** [comment]
Well in fact I launched the worker with the secret "prout", I just missed the copy/paste. I launched this : `./nexrender-worker-macos --host=http://localhost:8000 --secret=prout`

The crc32 returned this : 5c32853e

**Comment by inlife** [comment]
ok that issue is fixed too, binaries are being assembled
it was quite a silly mistake from my side

**Comment by inlife** [comment]
i ended up adding a big error message mainly for win and also probably for mac, if the chmod wont work

![image](https://user-images.githubusercontent.com/2182108/52302456-eb88fc80-2995-11e9-8467-449760b20358.png)

**Comment by HarryLafranc** [comment]
Thanks for your fast replies and fixes ! I'll try this out today and let you know if I find anything else !

**Comment by HarryLafranc** [comment]
Hey,

Just a note on the README file, on "Using API" in the example, there is a bracket at the wrong place :

```
result.on('finished', job) => console.log('project rendering finished'))
```

should be 

```
result.on('finished', job => console.log('project rendering finished'))
```

**Comment by inlife** [comment]
oh yes, thank you

**Comment by HarryLafranc** [comment]
Also, it seems that when downloading assets from a https URL, the worker crashes : 

```
[GCLwxpMu4_y8epl_k_BEo] error occurred: Error: unknown URI protocol provided: https
    at download (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\download.js:0:0)
    at module.exports.promises.concat.job.assets.map.asset (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\download.js:0:0)
    at Array.map (<anonymous>)
    at module.exports (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\tasks\download.js:0:0)
    at module.exports (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\helpers\state.js:0:0)
    at Promise.resolve.then.then.job (C:\snapshot\nexrender\packages\nexrender-worker\node_modules\@nexrender\core\src\index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by inlife** [comment]
yes, indeed

**Comment by inlife** [comment]
pushed a fix

**Comment by HarryLafranc** [comment]
Awesome, thanks a lot !

**Comment by egradman** [comment]
just a quick note:
as of alpha-10, the size of the `nexrender-cli-macos` binary was ~43MB.  Since then, it's ballooned to ~163MB.

**Comment by inlife** [comment]
yep, it now includes binary for ffmpeg (action-encode)
and unfortunately for now it has both macos and win32 binaries inside
i havent yet figured out a way to include only one of them

**Comment by itsnaresh** [comment]
Because I provided wrong composition name I am getting following error which is wrong[I am running though worker)

Wrong message:
=============
Error:=>Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg)
[DglwAofZLyDw5QU_R8vVk] error occurred: Error: Error loading postrender module @nexrender/action-encode: Error: Error in action-encode module (ffmpeg)


Right Message [Commnad Line Renderer]
===========================
ERROR: No comp was found with the given name.


https://github.com/inlife/nexrender/blob/master/packages/nexrender-core/src/assets/commandLineRenderer.jsx


Question 
========

How can I get these messages in worker so that I can handle them in right way

**Comment by inlife** [comment]
Error handling is a bit rough atm, I hope we will find a way to work it out more properly in the next updates.
