### ISSUE TITLE
How to add custom action?

### ISSUE THREAD

**Issue by bshelton** [inlife/nexrender#919]
I've published a npm module here - https://www.npmjs.com/package/@linkedlabs/nexrender-action-add-audio that I want to add as a postrender action. I've tested this locally by pointing directly to my index.js file and it worked. However, when I install my package globally, and use "@linkedlabs/nexrender-action-add-audio" as the module, nexrender can't find it.

```           
 {
                "module": "@linkedlabs/nexrender-action-add-audio",
                "output": "encoded2.mp4"
   },
```

```
> job rendering failed
NestedError: Could not require module '@linkedlabs/nexrender-action-add-audio'
    at requireg (/snapshot/nexrender/packages/nexrender-core/node_modules/requireg/lib/requireg.js:14:11)
    at /snapshot/nexrender/packages/nexrender-core/src/tasks/actions.js
Caused By: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:388:5)
    at validateString (node:internal/validators:114:11)
    at Module.require (node:internal/modules/cjs/loader:1005:3)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireg (/snapshot/nexrender/packages/nexrender-core/node_modules/requireg/lib/requireg.js:12:12)
    at /snapshot/nexrender/packages/nexrender-core/src/tasks/actions.js {
  nested: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
      at new NodeError (node:internal/errors:388:5)
      at validateString (node:internal/validators:114:11)
      at Module.require (node:internal/modules/cjs/loader:1005:3)
      at Module.require (pkg/prelude/bootstrap.js:1851:31)
      at require (node:internal/modules/cjs/helpers:102:18)
      at requireg (/snapshot/nexrender/packages/nexrender-core/node_modules/requireg/lib/requireg.js:12:12)
      at /snapshot/nexrender/packages/nexrender-core/src/tasks/actions.js {
    code: 'ERR_INVALID_ARG_TYPE'
  }
```

**Comment by inlife** [comment]
Did you figure out the issue @bshelton ?
