### ISSUE TITLE
TypeError: Cannot set property 'state' of undefined

### ISSUE THREAD

**Issue by egradman** [inlife/nexrender#92]
First of all, this is an _amazing_ project.  It's working great!

I'm getting a weird error on macos, ae2017.

```
> job rendering failed
TypeError: Cannot set property 'state' of undefined
    at module.exports (/snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/helpers/state.js:0:0)
    at Promise.resolve.then.then.then.then.then.then.then.job (/snapshot/nexrender/packages/nexrender-cli/node_modules/@nexrender/core/src/index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The render was successful, and the movie was correctly copied to the destination.  But I still get the error even though it works.
\

```
{
  "template": {
    "src": "file:///Users/egradman/dev/vr_loop/vr.aepx",
    "composition": "Main",
    "outputModule": "h264"
  },
  "assets": [
    {
      "type": "data",
      "layerName": "title",
      "property": "Source Text",
      "value": "Hello!"
    }
  ],
  "actions": {
    "prerender": [],
    "postrender": [
      {
        "module": "@nexrender/action-copy",
        "output": "/Users/egradman/dev/vr_loop/vr.mov"
      }
    ]
  }
}
```

**Comment by inlife** [comment]
oh, thank you for the report, looking into it!

**Comment by inlife** [comment]
indeed there was an issue related to action-copy, it didnt return the job properly
fixed that, and published a new build, thank you again!

**Comment by egradman** [comment]
fixed it for me!  thanks.
