### ISSUE TITLE
 Does Necklander support After Effects 2023? Is 2024 not supported?

### ISSUE THREAD

**Issue by DongJu-Na** [inlife/nexrender#944]
```
// job.json
{
  "template": {
    "src": "file:///c:/test.aep",
    "composition": "main",
    "outputModule": "H.264 - Match Render Settings - 15 Mbps",
    "outputExt": "mp4",
    "settingsTemplate": "Best Settings"
  },
  "aerender": "file://E:/After.Effects.2024/Adobe After Effects 2024/Support Files/aerender.exe"
}

```

nexrender-cli --file job.json
Not working 
Help me..

```
> starting nexrender-cli
C:\Users\DONGJU\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\index.js:62
        throw new Error('you should provide a proper path to After Effects\' "aerender" binary')
        ^

Error: you should provide a proper path to After Effects' "aerender" binary
    at Object.init (C:\Users\DONGJU\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\index.js:62:15)
    at Object.<anonymous> (C:\Users\DONGJU\AppData\Roaming\npm\node_modules\@nexrender\cli\src\bin.js:242:22)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by JamesBotterill** [comment]
Can you remove the . From the After.Effects.2024 path, that doesn’t look right. Obviously you’ll need to rename the folder and to match the path

**Comment by inlife** [comment]
Also, it would make sense to remove `file://` protocol in the beginning, since it's not related to the asset

**Comment by DongJu-Na** [comment]
@JamesBotterill 
@inlife 
Thank you both for your replies.

```
C:\Users\DONGJU\Desktop\test>nexrender-cli -f job.json -b "E:/After.Effects.2024/Adobe After Effects 2024/Support Files/aerender.exe"
> starting nexrender-cli
checking After Effects command line renderer patch...
command line patch already is in place
[wAaPQo-5LI9VaLc7FepRX] setting up job...
[wAaPQo-5LI9VaLc7FepRX] working directory is: C:\Users\DONGJU\AppData\Local\Temp\nexrender\wAaPQo-5LI9VaLc7FepRX
[wAaPQo-5LI9VaLc7FepRX] applying predownload actions...
[wAaPQo-5LI9VaLc7FepRX] downloading assets...
[wAaPQo-5LI9VaLc7FepRX] applying postdownload actions...
[wAaPQo-5LI9VaLc7FepRX] applying prerender actions...
[wAaPQo-5LI9VaLc7FepRX] running script assemble...
[wAaPQo-5LI9VaLc7FepRX] rendering job...
[wAaPQo-5LI9VaLc7FepRX] -- D E P R E C A T I O N: --

nexrender is changing the default aerender log path to the project folder.
This is done to streamline the log management and enable efficient log cleanup.

If you want to keep the old behavior and mute this message, please set the environment variable NEXRENDER_ENABLE_AELOG_LEGACY_TEMP_FOLDER to true.
If you want to switch to the new behavior, please set the environment variable NEXRENDER_ENABLE_AELOG_PROJECT_FOLDER to true.

Right now, the old behavior is still the default, but this will change in the next minor releases.
Estimated date of change to the new behavior: 2023-06-01.

[wAaPQo-5LI9VaLc7FepRX] rendering reached an error: No comp was found with the given name.

[wAaPQo-5LI9VaLc7FepRX] rendering took ~14.15 sec.
[wAaPQo-5LI9VaLc7FepRX] writing aerender job log to: C:\Users\DONGJU\AppData\Local\Temp\nexrender\aerender-wAaPQo-5LI9VaLc7FepRX.log
WARNING:After Effects ���: ������Ʈ�� �۲��� �����Ǿ����ϴ�.

Running Script: C:\Users\DONGJU\AppData\Local\Temp\nexrender\wAaPQo-5LI9VaLc7FepRX\nexrender-wAaPQo-5LI9VaLc7FepRX-script.jsx
aerender ERROR: No comp was found with the given name.

[wAaPQo-5LI9VaLc7FepRX] cleaning up...
> job rendering failed
Error: Couldn't find a result file: C:\Users\DONGJU\AppData\Local\Temp\nexrender\wAaPQo-5LI9VaLc7FepRX\result.avi
    at ChildProcess.<anonymous> (C:\Users\DONGJU\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\render.js:295:31)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)

```


In job.json
Can you tell me what the "composition" key means?

**Comment by DongJu-Na** [comment]
[Free Modern Fast Promo.zip](https://github.com/inlife/nexrender/files/13523431/Free.Modern.Fast.Promo.zip)

I would like to make the attached After Effects file into a video using nexrender-cli. Could you please tell me how?

**Comment by inlife** [comment]
Seems like you created your job with a wrong comp id

> rendering reached an error: No comp was found with the given name.
