### ISSUE TITLE
Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by lincolnlemos** [inlife/nexrender#96]
I'm trying to add a simple data asset and I'm getting this error.

`Error message: Parameter "url" must be a string, not undefined
TypeError: Parameter "url" must be a string, not undefined`

This only occurs after I add this block on my assets array.
```JSON
{
 "type": "data",
 "layerName": "Title",
 "property": "Source Text",
 "value": "Something with a character",
},

```
Below is the full error log on my terminal

```
Error message: Parameter "url" must be a string, not undefined
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at module.exports (/Volumes/Arquivos/Youtube/Animals/farm-animals/node_modules/download/index.js:48:21)
    at Promise.all.project.assets.map.asset (/Volumes/Arquivos/Youtube/Animals/farm-animals/node_modules/nexrender/renderer/tasks/download.js:23:22)
    at Array.map (<anonymous>)
    at Promise (/Volumes/Arquivos/Youtube/Animals/farm-animals/node_modules/nexrender/renderer/tasks/download.js:22:36)
    at new Promise (<anonymous>)
    at module.exports (/Volumes/Arquivos/Youtube/Animals/farm-animals/node_modules/nexrender/renderer/tasks/download.js:9:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:3512) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 127.0.0.1:23234
    at ClientRequest.req.once.err (/Volumes/Arquivos/Youtube/Animals/farm-animals/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:3512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas?

**Comment by inlife** [comment]
hello @lincolnlemos 
do you have only one asset, or there are more ?
it seems to me something goes wrong with asset array you have, could you please provide whole json for your job?
thank you!

**Comment by inlife** [comment]
actually, when i looked at the error message second time, i noticed an error
```
UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 127.0.0.1:23234
```
are you sure your other assets are properly accessible ?

**Comment by inlife** [comment]
also, on third look i noticed another \*minor\* issue on your side :D
from your error stack seems like you are using "nexrender" package from the stable branch, an older version which doesnt support the asset example you provided in your message

i would recommend reading up [Migrating from v0.x](https://github.com/inlife/nexrender#migrating-from-v0x) part of the readme, and probably then following a Usage part in more detailed manner

**Comment by lincolnlemos** [comment]
Hmm.. Ok. I'm not sure If the other assets are available.
I installed today and I'm playing with the boilerplate project.

The other assets like below don't give me error message:
```JSON
{ "type": "script",  "name": "scripts.js",         "src": `http://localhost:${port}/assets/scripts.js` },
`
The error only came when I add this type data.

I will take a look at the link. Thank you

**Comment by inlife** [comment]
yes, as you might've noticed boilerplate project uses an older version
that's actually a good point, i need to add that information to the boilerplate readme

i would suggest not look at the boilerplate project at all right now, and focus only on this repo readme file, it should cover most of the stuff you would probably ever need to know in regards of nexrender

**Comment by lincolnlemos** [comment]
Thanks buddy. I will start from scratch. After I learn, I will try to help you edit the boilerplate.
Thanks for the project. Looks very interesting!

**Comment by inlife** [comment]
thank you!
